#!/usr/bin/env python3
"""
Linguistic Guardian — enforces English-only content in .agent/, docs/, wiki/.

Excludes files that legitimately contain Cyrillic:
  - prompt-localizer.md: a translation agent that needs Cyrillic examples
  - adr-headroom-integration.md: historical ADR with Russian context
  - obsidian-integration.md: integration guide for Russian-speaking users
  - files in tasks/done/ and archive/: frozen historical artifacts
"""
import subprocess
import sys
from pathlib import Path

# Antigravity Standard: Path Resolution
REPO_ROOT = Path(__file__).resolve().parents[3]

# Files that LEGITIMATELY contain Cyrillic (translation agents, historical ADRs,
# integration guides for non-English-speaking users, frozen archives, caches).
# Add to this list ONLY with explicit justification in PR description.
CYRILLIC_ALLOWED_FILES = {
    # Translation agent — needs Cyrillic examples
    ".agent/agents/specialists/prompt-localizer.md",
    ".claude/agents/prompt-localizer.md",
    ".opencode/agents/prompt-localizer.md",
    # Historical ADR (written in Russian, frozen for reference)
    "wiki/decisions/adr-headroom-integration.md",
    # Russian-language integration guide
    "obsidian-integration.md",
    # Russian-language model recommendations
    "recomended-free-models.md",
    "gibrid-local-ll.md",
    "wiki/ARCHITECTURE.md",
    # Historical task cards (frozen, archive-only)
    "tasks/done/2026-07-06-arbor-session-dead-ends-registry.md",
    "tasks/done/2026-07-06-arbor-epic-integration-overview.md",
    "tasks/done/2026-07-06-arbor-hypothesis-tree-auto-healing.md",
    "tasks/done/2026-07-06-arbor-isolated-prototyping-worktrees.md",
    # Auto-trace / runtime output (regenerated each session)
    ".agent/tmp/response.md",
    "wiki/status.md",
    ".agent/rules/LESSONS_LEARNED.md",  # Contains Cyrillic entries from past sessions
    # LLM response caches (auto-generated, may contain Cyrillic from LLM responses)
    ".agent/tmp/llm_cache/",
    # Bus outputs (runtime data, auto-generated by agent runs)
    ".agent/bus/outputs/",
    # Legacy Go broker (has Cyrillic test fixtures and Russian comments;
    # pending separate refactor epic — it does NOT compile anyway, see
    # the .agent/mcp-llm-broker/README for the build-error context)
    ".agent/mcp-llm-broker/",
    # Router rules intentionally bilingual (English + Russian routing keywords)
    ".agent/config/router_rules.json",
}


def check_cyrillic():
    """
    Search for Cyrillic characters in critical directories.
    Excludes binary files and specific patterns if needed.
    """
    print("🔍 Checking for Cyrillic characters...")

    # Critical directories to check
    dirs = [".agent", "docs", "wiki"]

    # Regex for Cyrillic: \u0400-\u04FF covers most Cyrillic characters
    pattern = '[\u0400-\u04FF]'

    found_issues = []

    for d in dirs:
        dir_path = REPO_ROOT / d
        if not dir_path.exists():
            continue

        try:
            # Use grep to find matches
            # -r: recursive, -P: perl-regex, -n: line numbers
            cmd = ["grep", "-rPn", pattern, str(dir_path)]
            result = subprocess.run(cmd, capture_output=True, text=True)

            if result.stdout:
                lines = result.stdout.splitlines()
                for line in lines:
                    if "Binary file" in line:
                        continue
                    # grep output is: "abs_path:lineno:content"
                    # Extract the path and check if it ends with any allowed file
                    parts = line.split(":", 1)
                    if len(parts) < 2:
                        found_issues.append(line)
                        continue
                    abs_path = parts[0]
                    # Check if this file is in the allowed list
                    # (matches either exact path or relative path)
                    is_allowed = False
                    for allowed in CYRILLIC_ALLOWED_FILES:
                        # Exact file match
                        if abs_path.endswith(allowed) or abs_path.endswith("/" + allowed):
                            is_allowed = True
                            break
                        # Directory-style allow (e.g. ".agent/tmp/llm_cache/")
                        # Match anywhere in the path (path may be absolute or relative)
                        if allowed.endswith("/") and (allowed in abs_path or "/" + allowed in abs_path):
                            is_allowed = True
                            break
                    if is_allowed:
                        continue
                    found_issues.append(line)
        except Exception as e:
            print(f"⚠️ Error checking {d}: {e}")

    if found_issues:
        print(f"❌ Found {len(found_issues)} Cyrillic artifacts:")
        for issue in found_issues[:10]:
            print(f"  {issue}")
        if len(found_issues) > 10:
            print(f"  ... and {len(found_issues) - 10} more.")
        return False

    print("✅ No Cyrillic artifacts found.")
    return True


def main():
    if not check_cyrillic():
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
