#!/usr/bin/env python3
"""
Linguistic Guardian — enforces English-only content in .agent/, docs/, wiki/, tasks/.

Excludes files that legitimately contain Cyrillic (see CYRILLIC_ALLOWED_FILES
below for the full, individually-justified list), including:
  - prompt-localizer.md: a translation agent that needs Cyrillic examples
  - adr-headroom-integration.md: historical ADR with Russian context
  - obsidian-integration.md: integration guide for Russian-speaking users
  - specific task cards (active and archived) written in Russian — each
    listed by name, not a blanket tasks/ or tasks/done/ exclusion
"""
import subprocess
import sys
from pathlib import Path

# Antigravity Standard: Path Resolution
REPO_ROOT = Path(__file__).resolve().parents[3]

# Files that LEGITIMATELY contain Cyrillic (translation agents, historical ADRs,
# integration guides for non-English-speaking users, frozen archives, caches).
# Add to this list ONLY with explicit justification in PR description.
CYRILLIC_ALLOWED_FILES = {
    # Translation agent — needs Cyrillic examples
    ".agent/agents/specialists/prompt-localizer.md",
    ".claude/agents/prompt-localizer.md",
    ".opencode/agents/prompt-localizer.md",
    # Historical ADR (written in Russian, frozen for reference)
    "wiki/decisions/adr-headroom-integration.md",
    # Russian-language integration guide
    "obsidian-integration.md",
    # Russian-language model recommendations
    "recomended-free-models.md",
    "gibrid-local-ll.md",
    "wiki/ARCHITECTURE.md",
    # Historical task cards (frozen, archive-only)
    "tasks/done/2026-07/2026-07-06-arbor-session-dead-ends-registry.md",
    "tasks/done/2026-07/2026-07-06-arbor-epic-integration-overview.md",
    "tasks/done/2026-07/2026-07-06-arbor-hypothesis-tree-auto-healing.md",
    "tasks/done/2026-07/2026-07-06-arbor-isolated-prototyping-worktrees.md",
    "tasks/done/2026-08/2026-08-03-architecture-md-drift-and-dead-code.md",
    "tasks/done/2026-08/2026-08-14-unify-task-card-template-single-source-of-truth.md",
    "tasks/done/2026-08/2026-08-29-agent-scripts-stale-tasks-done-paths.md",
    "tasks/done/2026-08/2026-08-29-task-archive-does-not-rewrite-references.md",
    # Active task cards authored in Russian (the project's working language for planning docs —
    # see tasks/README.md history). Add new active cards here as they're written; once archived to
    # tasks/done/YYYY-MM/ move the entry up into the "historical task cards" group above instead of
    # leaving it here dead (that's exactly the drift the two cards above this comment were about).
    "tasks/2026-08-03-local-writing-agent-loop.md",
    # Auto-trace / runtime output (regenerated each session)
    ".agent/tmp/response.md",
    "wiki/status.md",
    ".agent/rules/LESSONS_LEARNED.md",  # Contains Cyrillic entries from past sessions
    # Deliberate Russian-language example phrases inside an English commit-permission rule (the
    # rule needs to recognize both languages, since the user sometimes confirms in Russian) — the
    # same example string appears in both the Gemini source and its Claude-side sync target.
    ".agent/rules/GEMINI.md",
    ".agent/rules/gemini/04_tier0_universal.md",
    # Arbor router training/eval sets: deliberately include Russian-language task prompts
    # ("lang": "ru") to verify the router classifies correctly across languages, not just English.
    ".agent/datasets/arbor-router-training/B_dev.jsonl",
    ".agent/datasets/arbor-router-training/B_test.jsonl",
    # LLM response caches (auto-generated, may contain Cyrillic from LLM responses)
    ".agent/tmp/llm_cache/",
    # Bus outputs (runtime data, auto-generated by agent runs)
    ".agent/bus/outputs/",
    # Legacy Go broker (has Cyrillic test fixtures and Russian comments;
    # pending separate refactor epic — it does NOT compile anyway, see
    # the .agent/mcp-llm-broker/README for the build-error context)
    ".agent/mcp-llm-broker/",
    # Router rules intentionally bilingual (English + Russian routing keywords)
    ".agent/config/router_rules.json",
}


def check_cyrillic():
    """
    Search for Cyrillic characters in critical directories.
    Excludes binary files and specific patterns if needed.
    """
    print("🔍 Checking for Cyrillic characters...")

    # Critical directories to check
    dirs = [".agent", "docs", "wiki", "tasks"]

    # Regex for Cyrillic: \u0400-\u04FF covers most Cyrillic characters
    pattern = '[\u0400-\u04FF]'

    found_issues = []

    for d in dirs:
        dir_path = REPO_ROOT / d
        if not dir_path.exists():
            continue

        try:
            # Use grep to find matches
            # -r: recursive, -P: perl-regex, -n: line numbers
            cmd = ["grep", "-rPn", pattern, str(dir_path)]
            result = subprocess.run(cmd, capture_output=True, text=True)

            if result.stdout:
                lines = result.stdout.splitlines()
                for line in lines:
                    if "Binary file" in line:
                        continue
                    # grep output is: "abs_path:lineno:content"
                    # Extract the path and check if it ends with any allowed file
                    parts = line.split(":", 1)
                    if len(parts) < 2:
                        found_issues.append(line)
                        continue
                    abs_path = parts[0]
                    # Check if this file is in the allowed list
                    # (matches either exact path or relative path)
                    is_allowed = False
                    for allowed in CYRILLIC_ALLOWED_FILES:
                        # Exact file match
                        if abs_path.endswith(allowed) or abs_path.endswith("/" + allowed):
                            is_allowed = True
                            break
                        # Directory-style allow (e.g. ".agent/tmp/llm_cache/")
                        # Match anywhere in the path (path may be absolute or relative)
                        if allowed.endswith("/") and (allowed in abs_path or "/" + allowed in abs_path):
                            is_allowed = True
                            break
                    if is_allowed:
                        continue
                    found_issues.append(line)
        except Exception as e:
            print(f"⚠️ Error checking {d}: {e}")

    if found_issues:
        print(f"❌ Found {len(found_issues)} Cyrillic artifacts:")
        for issue in found_issues[:10]:
            print(f"  {issue}")
        if len(found_issues) > 10:
            print(f"  ... and {len(found_issues) - 10} more.")
        return False

    print("✅ No Cyrillic artifacts found.")
    return True


def main():
    if not check_cyrillic():
        sys.exit(1)
    sys.exit(0)


if __name__ == "__main__":
    main()
