#!/usr/bin/env python3
"""Autonomous Reviewer Cron — Daily codebase audit that generates task cards.

Called by self-driving-ops.yml on a daily schedule. Scans the repository for:
  - Documentation drift (code vs wiki)
  - Missing or broken infrastructure
  - Roadmap items not yet converted to tasks
  - Stale or duplicate task cards
  - Agent/skill coverage gaps

Produces task cards in tasks/ for any issues found, then pushes a workspace health
summary to the context bus.
"""
import sys
import subprocess
from pathlib import Path
from datetime import datetime
import re

sys.path.append(str(Path(__file__).resolve().parent))
from lib.paths import REPO_ROOT
from lib.common import load_json_safe, save_json_atomic

TASKS_DIR = REPO_ROOT / "tasks"
AUDIT_LOG = REPO_ROOT / "wiki" / "archive" / "audit-log.md"


def slugify(text: str) -> str:
    text = text.lower()
    text = re.sub(r"[^a-z0-9]+", "-", text)
    return text.strip("-")[:40]


def task_exists(slug: str) -> bool:
    if not TASKS_DIR.exists():
        return False
    return any(f.name.endswith(f"-{slug}.md") for f in TASKS_DIR.glob("*.md"))


def create_task(tag: str, title: str, body: str, agent: str = "reviewer", priority: str = "Medium") -> str:
    TASKS_DIR.mkdir(parents=True, exist_ok=True)
    date_str = datetime.now().strftime("%Y-%m-%d")
    slug = slugify(title)
    filename = f"{date_str}-{slug}.md"
    filepath = TASKS_DIR / filename

    if filepath.exists():
        return f"EXISTS: {filename}"

    content = f"""# [{tag}] {title}

**Date**: {date_str}
**Agent**: `{agent}`
**Priority**: {priority}
**Source**: autonomous_reviewer_cron

## Problem
{body}

## Acceptance Criteria
- [ ] Investigate and resolve the issue described above
- [ ] Add a lesson to LESSONS_LEARNED.md if applicable
- [ ] Verify fix passes status_report health check

## Context
Auto-generated by autonomous daily audit.
"""
    filepath.write_text(content, encoding="utf-8")
    return f"CREATED: {filename}"


def check_drift() -> list[str]:
    """Run drift_detector and return list of drift issues."""
    issues = []
    try:
        import drift_detector
        drifts = drift_detector.detect_drift()
        for d in drifts:
            issues.append(str(d))
    except Exception as e:
        issues.append(f"drift_detector failed: {e}")
    return issues


def check_missing_infrastructure() -> list[dict]:
    """Check for missing dirs/files that agents depend on."""
    checks = [
        (TASKS_DIR, "tasks/ directory missing — agent task queue broken"),
        (REPO_ROOT / "wiki", "wiki/ directory missing — BMAD artifacts have no home"),
        (REPO_ROOT / ".agent" / "rules" / "LESSONS_LEARNED.md", "LESSONS_LEARNED.md missing — experience base broken"),
        (REPO_ROOT / ".agent" / "bus", "context bus directory missing"),
        (REPO_ROOT / "wiki" / "sprints", "wiki/sprints/ missing — sprint board has no home"),
    ]
    missing = []
    for path, message in checks:
        if not path.exists():
            missing.append({"path": str(path), "message": message})
    return missing


def check_roadmap_tasks() -> list[str]:
    """Find roadmap items in 'Now' section that have no corresponding task card."""
    roadmap_path = REPO_ROOT / "wiki" / "ROADMAP.md"
    if not roadmap_path.exists():
        return []

    content = roadmap_path.read_text(encoding="utf-8")
    in_now_section = False
    pending = []

    for line in content.splitlines():
        if "🔴 Now" in line or "Sprint 1" in line:
            in_now_section = True
            continue
        if in_now_section and line.startswith("## "):
            break
        if in_now_section and line.startswith("|") and "🔄" in line:
            parts = [p.strip() for p in line.split("|")]
            if len(parts) > 1:
                title = parts[1].strip()
                if title and title != "What":
                    pending.append(title)

    untracked = []
    for item in pending:
        slug = slugify(item[:40])
        if not task_exists(slug):
            untracked.append(item)
    return untracked


def check_stale_tasks() -> list[str]:
    """Find task cards older than 14 days that are still open."""
    if not TASKS_DIR.exists():
        return []
    stale = []
    today = datetime.now()
    for f in TASKS_DIR.glob("*.md"):
        if f.name == ".gitkeep":
            continue
        m = re.match(r"^(\d{4}-\d{2}-\d{2})-", f.name)
        if m:
            try:
                task_date = datetime.strptime(m.group(1), "%Y-%m-%d")
                age = (today - task_date).days
                if age > 14:
                    stale.append(f"{f.name} (age: {age}d)")
            except ValueError:
                pass
    return stale


def run_health_check() -> tuple[int, dict]:
    """Run status_report health check and return score + metrics."""
    try:
        sys.path.insert(0, str(REPO_ROOT / ".agent" / "scripts"))
        import status_report
        score, metrics = status_report.calculate_health()
        return score, metrics
    except Exception as e:
        return 100, {"error": str(e)}


def write_audit_log(results: dict) -> None:
    AUDIT_LOG.parent.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    entry = f"\n## Audit — {timestamp}\n\n"
    entry += f"- Health score: {results['health_score']}/100\n"
    entry += f"- Drift issues: {len(results['drift'])}\n"
    entry += f"- Missing infra: {len(results['missing_infra'])}\n"
    entry += f"- Untracked roadmap items: {len(results['roadmap_pending'])}\n"
    entry += f"- Stale tasks: {len(results['stale_tasks'])}\n"
    entry += f"- Tasks created: {len(results['tasks_created'])}\n"

    if results["tasks_created"]:
        entry += "\n**Tasks created:**\n"
        for t in results["tasks_created"]:
            entry += f"  - {t}\n"

    existing = AUDIT_LOG.read_text(encoding="utf-8") if AUDIT_LOG.exists() else "# Autonomous Audit Log\n"
    with open(AUDIT_LOG, "w", encoding="utf-8") as f:
        f.write(existing + entry)


def main() -> None:
    print(f"🤖 Autonomous Reviewer Cron — {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}")
    print("=" * 60)

    results = {
        "health_score": 100,
        "drift": [],
        "missing_infra": [],
        "roadmap_pending": [],
        "stale_tasks": [],
        "tasks_created": [],
    }

    # 1. Health check
    print("🔍 Running health check...")
    score, metrics = run_health_check()
    results["health_score"] = score
    print(f"   Health: {score}/100 — {metrics}")

    # 2. Drift detection
    print("📐 Checking documentation drift...")
    drift_issues = check_drift()
    results["drift"] = drift_issues
    if drift_issues:
        print(f"   Found {len(drift_issues)} drift issue(s)")
        for issue in drift_issues[:3]:
            slug = slugify(str(issue)[:40])
            if not task_exists(slug):
                result = create_task(
                    "CHORE", f"Fix doc drift: {str(issue)[:60]}",
                    f"Drift detected by drift_detector.py:\n{issue}",
                    agent="documentation-writer",
                )
                results["tasks_created"].append(result)
    else:
        print("   No drift detected")

    # 3. Infrastructure checks
    print("🏗️  Checking infrastructure...")
    missing = check_missing_infrastructure()
    results["missing_infra"] = missing
    for item in missing:
        print(f"   MISSING: {item['message']}")
        slug = slugify(item["message"][:40])
        if not task_exists(slug):
            result = create_task(
                "INFRA", f"Restore missing: {item['path'].split('/')[-1]}",
                item["message"],
                agent="devops-engineer",
                priority="High",
            )
            results["tasks_created"].append(result)

    # 4. Roadmap pending items
    print("🗺️  Scanning roadmap for untracked items...")
    pending = check_roadmap_tasks()
    results["roadmap_pending"] = pending
    for item in pending:
        print(f"   Untracked: {item[:60]}")
        result = create_task(
            "STORY", item[:80],
            f"Roadmap item from 'Now' sprint not yet converted to a task card:\n{item}",
            agent="orchestrator",
            priority="High",
        )
        results["tasks_created"].append(result)

    # 5. Stale tasks
    print("🕰️  Checking for stale task cards...")
    stale = check_stale_tasks()
    results["stale_tasks"] = stale
    if stale:
        print(f"   {len(stale)} stale task(s) found:")
        for s in stale:
            print(f"   - {s}")

    # 6. Write audit log
    write_audit_log(results)

    # 7. Summary
    print("\n" + "=" * 60)
    total_tasks = len(results["tasks_created"])
    if total_tasks:
        print(f"✅ Audit complete — {total_tasks} task card(s) created in tasks/")
        for t in results["tasks_created"]:
            print(f"   {t}")
    else:
        print("✅ Audit complete — workspace is clean, no new tasks needed")

    if results["stale_tasks"]:
        print(f"\n⚠️  {len(results['stale_tasks'])} stale task(s) need attention (>14 days old)")

    sys.exit(0)


if __name__ == "__main__":
    main()
