#!/usr/bin/env python3
"""
sync_agents.py — Generate .claude/ and .opencode/ agent layers from .agent/

This script universalizes the agent infrastructure by syncing the source of truth (.agent/)
to client-specific directories (.claude/ for Claude Code, .opencode/ for OpenCode).

Usage:
    python3 .agent/scripts/sync_agents.py --target claude
    python3 .agent/scripts/sync_agents.py --target opencode
"""

import argparse
import sys
import os
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.parent
AGENTS_SRC    = REPO_ROOT / ".agent" / "agents"
WORKFLOWS_SRC = REPO_ROOT / ".agent" / "workflows"
SKILLS_SRC    = REPO_ROOT / ".agent" / "skills"

# Targets Configuration
TARGETS = {
    "claude": {
        "agents_out":   REPO_ROOT / ".claude" / "agents",
        "commands_out": REPO_ROOT / ".claude" / "commands",
        "header": "<!-- GENERATED by sync_agents.py (target: claude) — do not edit directly -->\n",
        "workflow_prefix": "wf-",
    },
    "opencode": {
        "agents_out":   REPO_ROOT / ".opencode" / "agents",
        "commands_out": REPO_ROOT / ".opencode" / "commands",
        "header": "<!-- GENERATED by sync_agents.py (target: opencode) — do not edit directly -->\n",
        "workflow_prefix": "", # OpenCode prefers direct names or categories
    }
}

WORKFLOW_DEFAULT_TOOLS = "Read, Grep, Glob, Bash, Write, Edit"

AGENT_DEFAULT_TOOLS: dict[str, str] = {
    "orchestrator":           "Read, Write, Edit, Bash, Grep, Glob, Agent",
    "analyst":                "Read, Write, Edit, Grep, Glob, Agent",
    "project-planner":        "Read, Write, Edit, Grep, Glob, Agent",
    "ai-engineer":            "Read, Write, Edit, Bash, Grep, Glob, Agent",
    "backend-specialist":     "Read, Write, Edit, Bash, Grep, Glob",
    "frontend-specialist":    "Read, Write, Edit, Bash, Grep, Glob",
    "crypto-go-architect":   "Read, Write, Edit, Bash, Grep, Glob",
    "database-architect":     "Read, Write, Edit, Bash, Grep, Glob",
    "mobile-developer":       "Read, Write, Edit, Bash, Grep, Glob",
    "game-developer":         "Read, Write, Edit, Bash, Grep, Glob",
    "devops-engineer":        "Read, Write, Edit, Bash, Grep, Glob",
    "k8s-engineer":           "Read, Write, Edit, Bash, Grep, Glob",
    "data-engineer":          "Read, Write, Edit, Bash, Grep, Glob",
    "grpc-architect":         "Read, Write, Edit, Bash, Grep, Glob",
    "test-engineer":          "Read, Write, Edit, Bash, Grep, Glob",
    "qa-automation-engineer": "Read, Write, Edit, Bash, Grep, Glob",
    "code-archaeologist":     "Read, Write, Edit, Bash, Grep, Glob",
    "debugger":               "Read, Bash, Grep, Glob",
    "performance-optimizer":  "Read, Bash, Grep, Glob, Write",
    "security-auditor":       "Read, Bash, Grep, Glob",
    "penetration-tester":     "Read, Bash, Grep, Glob",
    "explorer-agent":         "Read, Bash, Grep, Glob",
    "git-master":             "Read, Bash, Grep, Glob",
    "reviewer":               "Read, Bash, Grep, Glob, Write",
    "documentation-writer":   "Read, Write, Edit, Grep, Glob",
    "wiki-architect":         "Read, Write, Edit, Grep, Glob",
    "rest-api-designer":      "Read, Write, Edit, Grep, Glob",
    "seo-specialist":         "Read, Write, Grep, Glob",
    "product-manager":        "Read, Write, Grep, Glob",
    "product-owner":          "Read, Write, Grep, Glob",
    "python-specialist":      "Read, Write, Edit, Bash, Grep, Glob",
}

COMMAND_META: dict[str, dict] = {
    "debug": {
        "argument-hint": "<error or issue description>",
        "allowed-tools": "Read, Grep, Glob, Bash",
    },
    "plan": {
        "argument-hint": "<feature or task to plan>",
        "allowed-tools": "Read, Grep, Glob, Write",
    },
    "create": {
        "argument-hint": "<app description, e.g. todo app with auth>",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit, Agent",
    },
    "deploy": {
        "argument-hint": "[environment: staging|production]",
        "allowed-tools": "Read, Bash",
    },
    "enhance": {
        "argument-hint": "<feature or improvement description>",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit",
    },
    "orchestrate": {
        "argument-hint": "<complex multi-domain task>",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit, Agent",
    },
    "status": {
        "argument-hint": "",
        "allowed-tools": "Read, Grep, Bash",
    },
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def parse_frontmatter(content: str) -> tuple[dict, str]:
    if not content.startswith("---"):
        return {}, content
    end = content.find("\n---", 3)
    if end == -1:
        return {}, content
    fm_block = content[3:end].strip()
    body = content[end + 4:].lstrip("\n")
    frontmatter: dict = {}
    for line in fm_block.splitlines():
        if ":" in line:
            key, _, val = line.partition(":")
            frontmatter[key.strip()] = val.strip()
    return frontmatter, body

def render_frontmatter(fm: dict) -> str:
    lines = ["---"]
    for key, val in fm.items():
        if val: lines.append(f"{key}: {val}")
        else: lines.append(f"{key}:")
    lines.append("---")
    return "\n".join(lines) + "\n"

def skill_exists(skill_name: str) -> bool:
    return (SKILLS_SRC / skill_name / "SKILL.md").exists()

# ---------------------------------------------------------------------------
# Builders
# ---------------------------------------------------------------------------

def build_agent_file(src_path: Path, target: str, is_workflow: bool = False) -> str:
    raw = src_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(raw)
    agent_name = src_path.stem
    skills = [s.strip() for s in fm.get("skills", "").split(",") if s.strip()]

    clean_fm: dict = {}
    clean_fm["name"] = fm.get("name", agent_name)
    if fm.get("description"): clean_fm["description"] = fm["description"]

    # Target specific logic
    if target == "claude":
        clean_fm["tools"] = fm.get("tools") or AGENT_DEFAULT_TOOLS.get(agent_name) or WORKFLOW_DEFAULT_TOOLS
    elif target == "opencode":
        # OpenCode might use standard frontmatter
        if fm.get("model"): clean_fm["model"] = fm["model"]

    parts = [TARGETS[target]["header"], render_frontmatter(clean_fm)]
    
    if is_workflow and target == "claude":
        body = body.replace("$ARGUMENTS", "_Context from user message is passed automatically by Claude Code._")
    
    parts.append(body)

    if skills and target == "claude" and not is_workflow:
        skill_lines = "\n".join(f"- `.agent/skills/{s}/SKILL.md`" for s in skills if skill_exists(s))
        if skill_lines:
            parts.append("\n---\n\n> **Skills** — read these files with the `Read` tool before starting:\n" + skill_lines + "\n")

    return "\n".join(parts)

def build_command_file(src_path: Path, target: str) -> str:
    raw = src_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(raw)
    name = src_path.stem
    meta = COMMAND_META.get(name, {})

    cmd_fm: dict = {}
    if fm.get("description"): cmd_fm["description"] = fm["description"]

    if target == "claude":
        cmd_fm["argument-hint"] = meta.get("argument-hint", "")
        cmd_fm["allowed-tools"] = meta.get("allowed-tools", WORKFLOW_DEFAULT_TOOLS)
    elif target == "opencode":
        # OpenCode commands often specify an agent or mode
        cmd_fm["agent"] = fm.get("agent", "orchestrator")
        if meta.get("argument-hint"):
            body = f"> Hint: {meta['argument-hint']}\n\n" + body

    parts = [TARGETS[target]["header"], render_frontmatter(cmd_fm), body]
    return "\n".join(parts)

# ---------------------------------------------------------------------------
# Sync Logic
# ---------------------------------------------------------------------------

def cleanup_orphans(target: str, expected_files: set, dry_run: bool):
    config = TARGETS[target]
    for out_dir in [config["agents_out"], config["commands_out"]]:
        if not out_dir.exists():
            continue
        for item in out_dir.glob("*.md"):
            if item not in expected_files:
                rel = item.relative_to(REPO_ROOT)
                if dry_run:
                    print(f"  [ORPHAN-DRY] {rel}")
                else:
                    item.unlink()
                    print(f"  🗑️ {rel}")

def get_profile_extra_agents(profile_name: str) -> set:
    if not profile_name:
        return set()
    profile_path = REPO_ROOT / ".github" / "profiles.yml"
    if not profile_path.exists():
        return set()
    try:
        import yaml
        with open(profile_path) as f:
            data = yaml.safe_load(f)
            return set(data.get("profiles", {}).get(profile_name, {}).get("extra_agents", []))
    except Exception:
        return set()

def should_include_agent(src: Path, profile_name: str, extra_agents: set) -> bool:
    if not profile_name:
        return True
    if src.stem in extra_agents:
        return True
    
    # Check frontmatter
    content = src.read_text()
    if not content.startswith("---"):
        return True # Universal if no frontmatter
        
    parts = content.split("---", 2)
    if len(parts) < 3:
        return True
        
    try:
        import yaml
        fm = yaml.safe_load(parts[1])
        agent_profiles = fm.get("profile", "")
        if not agent_profiles:
            return True # Universal
        
        allowed = [p.strip() for p in str(agent_profiles).split(",")]
        return profile_name in allowed
    except Exception:
        return True # Fallback to include

def sync(target: str, dry_run: bool = False, check: bool = False, only_agent: str = "", profile: str = "", no_commands: bool = False, no_workflows: bool = False):
    config = TARGETS[target]
    config["agents_out"].mkdir(parents=True, exist_ok=True)
    config["commands_out"].mkdir(parents=True, exist_ok=True)

    print(f"\n=== Syncing TARGET: {target} ===")
    
    expected_files = set()
    extra_agents = get_profile_extra_agents(profile)

    # 1. Specialist Agents
    agent_files = sorted(AGENTS_SRC.rglob("**/*.md"))
    if only_agent:
        agent_files = [f for f in agent_files if f.stem == only_agent]
    
    for src in agent_files:
        if not should_include_agent(src, profile, extra_agents):
            continue
            
        out_path = config["agents_out"] / src.name
        expected_files.add(out_path)
        content = build_agent_file(src, target, is_workflow=False)
        _write(out_path, content, dry_run, check)

    # 2. Workflows as Agents (Claude only usually)
    if target == "claude" and not no_workflows:
        for src in sorted(WORKFLOWS_SRC.glob("*.md")):
            # Workflows are generally universal unless we add profile support for them too
            out_path = config["agents_out"] / f"wf-{src.name}"
            expected_files.add(out_path)
            content = build_agent_file(src, target, is_workflow=True)
            _write(out_path, content, dry_run, check)

    # 3. Workflows as Commands
    if not no_commands:
        for src in sorted(WORKFLOWS_SRC.glob("*.md")):
            out_path = config["commands_out"] / src.name
            expected_files.add(out_path)
            content = build_command_file(src, target)
            _write(out_path, content, dry_run, check)

    # 4. Cleanup
    if not only_agent and not profile:
        cleanup_orphans(target, expected_files, dry_run)

def _write(path: Path, content: str, dry_run: bool, check: bool):
    rel = path.relative_to(REPO_ROOT)
    if dry_run:
        print(f"  [DRY] {rel}")
        return
    if check:
        if not path.exists():
            print(f"  [MISSING] {rel}")
            sys.exit(1)
        existing = path.read_text()
        if existing != content:
            print(f"  [DRIFT] {rel}")
            sys.exit(1)
        return
    path.write_text(content)
    print(f"  ✓ {rel}")

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", choices=["claude", "opencode"], default="claude")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--agent", metavar="NAME", default="")
    parser.add_argument("--profile", metavar="NAME", default="")
    parser.add_argument("--no-commands", action="store_true")
    parser.add_argument("--no-workflows", action="store_true")
    args = parser.parse_args()

    sync(args.target, args.dry_run, args.check, args.agent, args.profile, args.no_commands, args.no_workflows)

if __name__ == "__main__":
    main()
