#!/usr/bin/env python3
"""
sync_claude_agents.py — Generate .claude/agents/ and .claude/commands/ from .agent/

Generates two output layers for Claude Code while keeping .agent/ unchanged for Antigravity:

  .agent/agents/*.md     → .claude/agents/*.md        (specialist subagents, @-invokable)
  .agent/workflows/*.md  → .claude/agents/wf-*.md     (workflow subagents, @-invokable)
  .agent/workflows/*.md  → .claude/commands/*.md       (slash commands, /name invokable)

Skills are NOT embedded. Instead, agents receive a "Read these files" instruction block.
This eliminates content duplication and the 100-line truncation limit.

Variant B+A approach:
  B — dual-compatible frontmatter: source files carry both `skills:` (Antigravity) and
      `tools:` (Claude Code). Use --patch-source-tools to write tools: into source files.
  A — dynamic skill loading: generated agents get a pointer section instead of inline content.

Usage:
    python3 .agent/scripts/sync_claude_agents.py
    python3 .agent/scripts/sync_claude_agents.py --dry-run
    python3 .agent/scripts/sync_claude_agents.py --agent debugger
    python3 .agent/scripts/sync_claude_agents.py --no-commands
    python3 .agent/scripts/sync_claude_agents.py --no-workflows
    python3 .agent/scripts/sync_claude_agents.py --profile go-service   # only profile agents
    python3 .agent/scripts/sync_claude_agents.py --patch-source-tools   # one-time migration

Distribution Profiles (Option A):
  Agents with no `profile:` frontmatter are universal — included in every profile.
  Agents with `profile: go-service, web-app` are only included when that profile matches.
  Available profiles: go-service, web-app, data-platform, mobile, game
"""

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.parent
AGENTS_SRC          = REPO_ROOT / ".agent" / "agents"
WORKFLOWS_SRC       = REPO_ROOT / ".agent" / "workflows"
SKILLS_SRC          = REPO_ROOT / ".agent" / "skills"
CLAUDE_AGENTS_OUT   = REPO_ROOT / ".claude" / "agents"
CLAUDE_COMMANDS_OUT = REPO_ROOT / ".claude" / "commands"

GENERATED_HEADER = "<!-- GENERATED by sync_claude_agents.py — do not edit directly -->\n"

WORKFLOW_DEFAULT_TOOLS = "Read, Grep, Glob, Bash, Write, Edit"

# Fallback tools per agent — used when source frontmatter has no `tools:` field.
# After running --patch-source-tools these become authoritative in the source files.
AGENT_DEFAULT_TOOLS: dict[str, str] = {
    # Coordination agents — need Agent tool to spawn subagents
    "orchestrator":           "Read, Write, Edit, Bash, Grep, Glob, Agent",
    "analyst":                "Read, Write, Edit, Grep, Glob, Agent",
    "project-planner":        "Read, Write, Edit, Grep, Glob, Agent",
    "ai-engineer":            "Read, Write, Edit, Bash, Grep, Glob, Agent",
    # Implementation agents
    "backend-specialist":     "Read, Write, Edit, Bash, Grep, Glob",
    "frontend-specialist":    "Read, Write, Edit, Bash, Grep, Glob",
    "crypto-go-architect":   "Read, Write, Edit, Bash, Grep, Glob",
    "database-architect":     "Read, Write, Edit, Bash, Grep, Glob",
    "mobile-developer":       "Read, Write, Edit, Bash, Grep, Glob",
    "game-developer":         "Read, Write, Edit, Bash, Grep, Glob",
    "devops-engineer":        "Read, Write, Edit, Bash, Grep, Glob",
    "k8s-engineer":           "Read, Write, Edit, Bash, Grep, Glob",
    "data-engineer":          "Read, Write, Edit, Bash, Grep, Glob",
    "grpc-architect":         "Read, Write, Edit, Bash, Grep, Glob",
    "test-engineer":          "Read, Write, Edit, Bash, Grep, Glob",
    "qa-automation-engineer": "Read, Write, Edit, Bash, Grep, Glob",
    "code-archaeologist":     "Read, Write, Edit, Bash, Grep, Glob",
    # Investigation agents — read-heavy, write only for reports
    "debugger":               "Read, Bash, Grep, Glob",
    "performance-optimizer":  "Read, Bash, Grep, Glob, Write",
    "security-auditor":       "Read, Bash, Grep, Glob",
    "penetration-tester":     "Read, Bash, Grep, Glob",
    "explorer-agent":         "Read, Bash, Grep, Glob",
    "git-master":             "Read, Bash, Grep, Glob",
    "reviewer":               "Read, Bash, Grep, Glob, Write",
    # Documentation / design agents
    "documentation-writer":   "Read, Write, Edit, Grep, Glob",
    "wiki-architect":         "Read, Write, Edit, Grep, Glob",
    "rest-api-designer":      "Read, Write, Edit, Grep, Glob",
    "seo-specialist":         "Read, Write, Grep, Glob",
    "product-manager":        "Read, Write, Grep, Glob",
    "product-owner":          "Read, Write, Grep, Glob",
}

# Claude Code slash-command metadata (added on top of Antigravity workflow content).
# argument-hint: shown in the command picker UI as a hint for what to type after /name
# allowed-tools: pre-approved tools; prevents permission prompts during command execution
COMMAND_META: dict[str, dict] = {
    "debug": {
        "argument-hint": "<error or issue description>",
        "allowed-tools": "Read, Grep, Glob, Bash",
    },
    "plan": {
        "argument-hint": "<feature or task to plan>",
        "allowed-tools": "Read, Grep, Glob, Write",
    },
    "create": {
        "argument-hint": "<app description, e.g. todo app with auth>",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit, Agent",
    },
    "deploy": {
        "argument-hint": "[environment: staging|production]",
        "allowed-tools": "Read, Bash",
    },
    "enhance": {
        "argument-hint": "<feature or improvement description>",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit",
    },
    "orchestrate": {
        "argument-hint": "<complex multi-domain task>",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit, Agent",
    },
    "brainstorm": {
        "argument-hint": "<topic or problem to explore>",
        "allowed-tools": "Read, Write",
    },
    "test": {
        "argument-hint": "[file or feature to test]",
        "allowed-tools": "Read, Grep, Glob, Bash, Write",
    },
    "status": {
        "argument-hint": "",
        "allowed-tools": "Read, Grep, Bash",
    },
    "preview": {
        "argument-hint": "[start|stop|status]",
        "allowed-tools": "Bash",
    },
    "ui-ux-pro-max": {
        "argument-hint": "<page or component to design>",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit",
    },
    "discovery": {
        "argument-hint": "[project idea or problem to solve]",
        "allowed-tools": "Read, Write",
    },
    "prd": {
        "argument-hint": "",
        "allowed-tools": "Read, Write",
    },
    "architecture-bmad": {
        "argument-hint": "",
        "allowed-tools": "Read, Write",
    },
    "stories": {
        "argument-hint": "",
        "allowed-tools": "Read, Write",
    },
    "sprint": {
        "argument-hint": "[sprint number]",
        "allowed-tools": "Read, Write",
    },
    "close-sprint": {
        "argument-hint": "[sprint number]",
        "allowed-tools": "Read, Write, Edit",
    },
    "reviewer": {
        "argument-hint": "[target path or scope]",
        "allowed-tools": "Read, Grep, Glob, Write, Bash",
    },
    "distill-experience": {
        "argument-hint": "",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit",
    },
    "release": {
        "argument-hint": "[version: patch|minor|major]",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit",
    },
    "wiki": {
        "argument-hint": "[audit|update|model]",
        "allowed-tools": "Read, Write, Edit, Grep, Glob",
    },
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def parse_frontmatter(content: str) -> tuple[dict, str]:
    """Split YAML frontmatter from body. Returns (frontmatter_dict, body)."""
    if not content.startswith("---"):
        return {}, content

    end = content.find("\n---", 3)
    if end == -1:
        return {}, content

    fm_block = content[3:end].strip()
    body = content[end + 4:].lstrip("\n")

    frontmatter: dict = {}
    for line in fm_block.splitlines():
        if ":" in line:
            key, _, val = line.partition(":")
            frontmatter[key.strip()] = val.strip()

    return frontmatter, body


def render_frontmatter(fm: dict) -> str:
    """Render frontmatter dict to YAML block."""
    lines = ["---"]
    for key, val in fm.items():
        if val:
            lines.append(f"{key}: {val}")
        else:
            lines.append(f"{key}:")
    lines.append("---")
    return "\n".join(lines) + "\n"


def parse_skills_list(value: str) -> list[str]:
    return [s.strip() for s in value.split(",") if s.strip()]


def agent_matches_profile(fm: dict, profile: str) -> bool:
    """Return True if this agent should be included in the given profile.

    Agents with no `profile:` frontmatter are universal — included in every profile.
    Agents with `profile: go-service, web-app` are only included when the requested
    profile is in that list.
    """
    if not profile:
        return True
    agent_profiles = parse_skills_list(fm.get("profile", ""))
    return not agent_profiles or profile in agent_profiles


def skill_exists(skill_name: str) -> bool:
    return (SKILLS_SRC / skill_name / "SKILL.md").exists()


# ---------------------------------------------------------------------------
# Builders
# ---------------------------------------------------------------------------

def build_claude_agent(src_path: Path, is_workflow: bool = False) -> str:
    """Build .claude/agents/*.md content from a source .agent/agents/ or workflows/ file.

    Specialist agents:
      - `skills:` is stripped from output frontmatter (Antigravity-only field)
      - `tools:` is taken from source frontmatter or AGENT_DEFAULT_TOOLS
      - A pointer block "Read these skill files before starting" replaces inline embedding

    Workflow agents:
      - $ARGUMENTS replaced with a Claude Code note (subagents receive context differently)
      - tools: defaults to WORKFLOW_DEFAULT_TOOLS
    """
    raw = src_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(raw)

    agent_name = src_path.stem
    skills = parse_skills_list(fm.get("skills", ""))

    clean_fm: dict = {}
    clean_fm["name"] = fm.get("name", agent_name)

    desc = fm.get("description", "")
    if desc:
        clean_fm["description"] = desc

    # tools: source frontmatter wins; fall back to per-agent default or workflow default
    tools = (
        fm.get("tools")
        or (None if is_workflow else AGENT_DEFAULT_TOOLS.get(agent_name))
        or WORKFLOW_DEFAULT_TOOLS
    )
    clean_fm["tools"] = tools

    model = fm.get("model", "")
    if model and model != "inherit":
        clean_fm["model"] = model

    parts = [GENERATED_HEADER, render_frontmatter(clean_fm)]

    if is_workflow:
        body = body.replace(
            "$ARGUMENTS",
            "_Context from user message is passed automatically by Claude Code._",
        )

    parts.append(body)

    # Dynamic skill loading — pointer block instead of embedded content.
    # The agent reads skill files on demand via its Read tool.
    # Antigravity loads the same skills dynamically via `skills:` frontmatter.
    if skills and not is_workflow:
        missing = [s for s in skills if not skill_exists(s)]
        if missing:
            print(f"  WARNING [{agent_name}]: skill(s) not found: {missing}")

        skill_lines = "\n".join(
            f"- `.agent/skills/{s}/SKILL.md`" for s in skills
        )
        parts.append(
            "\n---\n\n"
            "> **Skills** — read these files with the `Read` tool before starting:\n"
            f"{skill_lines}\n"
        )

    return "\n".join(parts)


def build_command(src_path: Path) -> str:
    """Build .claude/commands/<name>.md content from a .agent/workflows/ file.

    Keeps $ARGUMENTS verbatim — both Antigravity and Claude Code commands use the same syntax.
    Adds Claude Code-specific frontmatter (argument-hint, allowed-tools) on top of the
    original description field, without touching any Antigravity workflow content.
    """
    raw = src_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(raw)

    name = src_path.stem
    meta = COMMAND_META.get(name, {})

    cmd_fm: dict = {}

    desc = fm.get("description", "")
    if desc:
        cmd_fm["description"] = desc

    hint = meta.get("argument-hint", "")
    if hint:
        cmd_fm["argument-hint"] = hint

    allowed = meta.get("allowed-tools", WORKFLOW_DEFAULT_TOOLS)
    cmd_fm["allowed-tools"] = allowed

    parts = [GENERATED_HEADER, render_frontmatter(cmd_fm)]
    parts.append(body)

    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Migration helper: write tools: into source agent files (Variant B)
# ---------------------------------------------------------------------------

def patch_source_tools(dry_run: bool = False) -> None:
    """Write `tools:` field into .agent/agents/*.md source files.

    This is a one-time migration step for Variant B (dual-compatible frontmatter).
    After running this, source files are directly usable by Claude Code without
    transformation — symlinks become viable, and the sync script only needs to
    handle workflows and the skill pointer block.

    Safe to re-run: skips files that already have `tools:` in frontmatter.
    """
    print("\n=== Patching source agent files with tools: (Variant B migration) ===")
    patched = 0
    skipped = 0

    for src in sorted(AGENTS_SRC.glob("*.md")):
        raw = src.read_text(encoding="utf-8")
        fm, body = parse_frontmatter(raw)

        if fm.get("tools"):
            print(f"  SKIP  {src.name}  (already has tools:)")
            skipped += 1
            continue

        agent_name = src.stem
        tools = AGENT_DEFAULT_TOOLS.get(agent_name)
        if not tools:
            print(f"  SKIP  {src.name}  (no entry in AGENT_DEFAULT_TOOLS)")
            skipped += 1
            continue

        # Inject tools: after description: in frontmatter
        fm_ordered: dict = {}
        for key in ("name", "description", "tools", "skills", "model"):
            if key == "tools":
                fm_ordered["tools"] = tools
            elif key in fm:
                fm_ordered[key] = fm[key]
        for key, val in fm.items():
            if key not in fm_ordered:
                fm_ordered[key] = val

        new_content = render_frontmatter(fm_ordered) + "\n" + body
        if dry_run:
            print(f"  [DRY] {src.name}  → tools: {tools}")
        else:
            src.write_text(new_content, encoding="utf-8")
            print(f"  ✓ {src.name}  → tools: {tools}")
        patched += 1

    print(f"\nPatched: {patched}  Skipped: {skipped}")


# ---------------------------------------------------------------------------
# Sync functions
# ---------------------------------------------------------------------------

_drift: list[str] = []  # populated in check mode


def _write_file(out_path: "Path", content: str, dry_run: bool, check: bool) -> None:
    """Write content to out_path, or in check/dry-run mode just report."""
    rel = out_path.relative_to(REPO_ROOT)
    if dry_run:
        print(f"  [DRY] {rel}")
        return
    if check:
        existing = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
        if existing != content:
            print(f"  [DRIFT] {rel}")
            _drift.append(str(rel))
        else:
            print(f"  [OK]    {rel}")
        return
    out_path.write_text(content, encoding="utf-8")
    print(f"  ✓ {rel}")


def sync_agents(dry_run: bool = False, only_agent: str = "", profile: str = "", check: bool = False) -> None:
    CLAUDE_AGENTS_OUT.mkdir(parents=True, exist_ok=True)

    agent_files = sorted(AGENTS_SRC.glob("*.md"))
    if only_agent:
        agent_files = [f for f in agent_files if f.stem == only_agent]
        if not agent_files:
            print(f"ERROR: agent '{only_agent}' not found in {AGENTS_SRC}")
            sys.exit(1)

    if profile:
        filtered = []
        for f in agent_files:
            fm, _ = parse_frontmatter(f.read_text(encoding="utf-8"))
            if agent_matches_profile(fm, profile):
                filtered.append(f)
        skipped = len(agent_files) - len(filtered)
        agent_files = filtered
        print(f"\n=== Syncing specialist agents ({len(agent_files)}, profile={profile!r}, skipped={skipped}) ===")
    else:
        print(f"\n=== Syncing specialist agents ({len(agent_files)}) ===")

    for src in agent_files:
        out_path = CLAUDE_AGENTS_OUT / src.name
        content = build_claude_agent(src, is_workflow=False)
        _write_file(out_path, content, dry_run, check)


def sync_workflows(dry_run: bool = False, check: bool = False) -> None:
    CLAUDE_AGENTS_OUT.mkdir(parents=True, exist_ok=True)

    workflow_files = sorted(WORKFLOWS_SRC.glob("*.md"))
    print(f"\n=== Syncing workflow agents ({len(workflow_files)}) ===")
    for src in workflow_files:
        out_path = CLAUDE_AGENTS_OUT / f"wf-{src.name}"
        content = build_claude_agent(src, is_workflow=True)
        _write_file(out_path, content, dry_run, check)


def sync_commands(dry_run: bool = False, check: bool = False) -> None:
    """Generate .claude/commands/ from .agent/workflows/.

    Each workflow becomes a /slash-command in Claude Code.
    $ARGUMENTS is preserved verbatim — compatible with both Antigravity and Claude Code.
    .agent/workflows/ files are never modified (Antigravity backward compatibility).
    """
    CLAUDE_COMMANDS_OUT.mkdir(parents=True, exist_ok=True)

    workflow_files = sorted(WORKFLOWS_SRC.glob("*.md"))
    print(f"\n=== Syncing slash commands ({len(workflow_files)}) ===")

    unknown = [f.stem for f in workflow_files if f.stem not in COMMAND_META]
    if unknown:
        print(f"  WARNING: no COMMAND_META entry for: {unknown}")
        print(f"  → These will use default tools: {WORKFLOW_DEFAULT_TOOLS}")

    for src in workflow_files:
        out_path = CLAUDE_COMMANDS_OUT / src.name
        content = build_command(src)
        _write_file(out_path, content, dry_run, check)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Sync .agent/ → .claude/agents/ and .claude/commands/")
    parser.add_argument("--dry-run", action="store_true", help="Print what would be written without writing")
    parser.add_argument("--check", action="store_true", help="Exit with code 1 if any file would change (CI mode)")
    parser.add_argument("--agent", metavar="NAME", help="Sync only one specialist agent by name")
    parser.add_argument(
        "--profile",
        metavar="NAME",
        help="Filter agents by distribution profile (go-service, web-app, data-platform, mobile, game). "
             "Universal agents (no profile: frontmatter) are always included.",
    )
    parser.add_argument("--no-workflows", action="store_true", help="Skip wf- workflow agents in .claude/agents/")
    parser.add_argument("--no-commands", action="store_true", help="Skip slash commands in .claude/commands/")
    parser.add_argument(
        "--patch-source-tools",
        action="store_true",
        help="One-time migration: write tools: into .agent/agents/*.md source files (Variant B)",
    )
    args = parser.parse_args()

    print(f"Repo root : {REPO_ROOT}")
    print(f"Agents out: {CLAUDE_AGENTS_OUT}")
    print(f"Commands  : {CLAUDE_COMMANDS_OUT}")

    if args.patch_source_tools:
        patch_source_tools(dry_run=args.dry_run)
        return

    check = args.check
    dry_run = args.dry_run

    sync_agents(dry_run=dry_run, only_agent=args.agent, profile=args.profile or "", check=check)

    if not args.agent:
        if not args.no_workflows:
            sync_workflows(dry_run=dry_run, check=check)
        if not args.no_commands:
            sync_commands(dry_run=dry_run, check=check)

    if check:
        if _drift:
            print(f"\nERROR: {len(_drift)} file(s) out of sync. Run 'make sync' to fix.")
            sys.exit(1)
        else:
            print("\nAll files in sync.")
    elif not dry_run:
        n_agents   = len(list(CLAUDE_AGENTS_OUT.glob("*.md")))
        n_commands = len(list(CLAUDE_COMMANDS_OUT.glob("*.md")))
        print(f"\nDone. agents: {n_agents}  commands: {n_commands}")


if __name__ == "__main__":
    main()
