#!/usr/bin/env python3
"""
sync_claude_agents.py — Generate .claude/agents/ and .claude/commands/ from .agent/

Generates two output layers for Claude Code while keeping .agent/ unchanged for Antigravity:

  .agent/agents/*.md     → .claude/agents/*.md        (specialist subagents, @-invokable)
  .agent/workflows/*.md  → .claude/agents/wf-*.md     (workflow subagents, @-invokable)
  .agent/workflows/*.md  → .claude/commands/*.md       (slash commands, /name invokable)

Usage:
    python3 .agent/scripts/sync_claude_agents.py
    python3 .agent/scripts/sync_claude_agents.py --dry-run
    python3 .agent/scripts/sync_claude_agents.py --agent debugger
    python3 .agent/scripts/sync_claude_agents.py --no-commands
    python3 .agent/scripts/sync_claude_agents.py --no-workflows
"""

import argparse
import sys
from pathlib import Path

SKILL_EMBED_MAX_LINES = 100
EMBED_END_MARKER = "<!-- EMBED_END -->"

REPO_ROOT = Path(__file__).parent.parent.parent
AGENTS_SRC       = REPO_ROOT / ".agent" / "agents"
WORKFLOWS_SRC    = REPO_ROOT / ".agent" / "workflows"
SKILLS_SRC       = REPO_ROOT / ".agent" / "skills"
CLAUDE_AGENTS_OUT   = REPO_ROOT / ".claude" / "agents"
CLAUDE_COMMANDS_OUT = REPO_ROOT / ".claude" / "commands"

GENERATED_HEADER = "<!-- GENERATED by sync_claude_agents.py — do not edit directly -->\n"

WORKFLOW_DEFAULT_TOOLS = "Read, Grep, Glob, Bash, Write, Edit"

# Claude Code slash-command metadata (added on top of Antigravity workflow content).
# argument-hint: shown in the command picker UI as a hint for what to type after /name
# allowed-tools: pre-approved tools; prevents permission prompts during command execution
COMMAND_META: dict[str, dict] = {
    "debug": {
        "argument-hint": "<error or issue description>",
        "allowed-tools": "Read, Grep, Glob, Bash",
    },
    "plan": {
        "argument-hint": "<feature or task to plan>",
        "allowed-tools": "Read, Grep, Glob, Write",
    },
    "create": {
        "argument-hint": "<app description, e.g. todo app with auth>",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit, Agent",
    },
    "deploy": {
        "argument-hint": "[environment: staging|production]",
        "allowed-tools": "Read, Bash",
    },
    "enhance": {
        "argument-hint": "<feature or improvement description>",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit",
    },
    "orchestrate": {
        "argument-hint": "<complex multi-domain task>",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit, Agent",
    },
    "brainstorm": {
        "argument-hint": "<topic or problem to explore>",
        "allowed-tools": "Read, Write",
    },
    "test": {
        "argument-hint": "[file or feature to test]",
        "allowed-tools": "Read, Grep, Glob, Bash, Write",
    },
    "status": {
        "argument-hint": "",
        "allowed-tools": "Read, Grep, Bash",
    },
    "preview": {
        "argument-hint": "[start|stop|status]",
        "allowed-tools": "Bash",
    },
    "ui-ux-pro-max": {
        "argument-hint": "<page or component to design>",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit",
    },
    "discovery": {
        "argument-hint": "[project idea or problem to solve]",
        "allowed-tools": "Read, Write",
    },
    "prd": {
        "argument-hint": "",
        "allowed-tools": "Read, Write",
    },
    "architecture-bmad": {
        "argument-hint": "",
        "allowed-tools": "Read, Write",
    },
    "stories": {
        "argument-hint": "",
        "allowed-tools": "Read, Write",
    },
    "sprint": {
        "argument-hint": "[sprint number]",
        "allowed-tools": "Read, Write",
    },
    "close-sprint": {
        "argument-hint": "[sprint number]",
        "allowed-tools": "Read, Write, Edit",
    },
    "reviewer": {
        "argument-hint": "[target path or scope]",
        "allowed-tools": "Read, Grep, Glob, Write, Bash",
    },
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def parse_frontmatter(content: str) -> tuple[dict, str]:
    """Split YAML frontmatter from body. Returns (frontmatter_dict, body)."""
    if not content.startswith("---"):
        return {}, content

    end = content.find("\n---", 3)
    if end == -1:
        return {}, content

    fm_block = content[3:end].strip()
    body = content[end + 4:].lstrip("\n")

    frontmatter: dict = {}
    for line in fm_block.splitlines():
        if ":" in line:
            key, _, val = line.partition(":")
            frontmatter[key.strip()] = val.strip()

    return frontmatter, body


def render_frontmatter(fm: dict) -> str:
    """Render frontmatter dict to YAML block."""
    lines = ["---"]
    for key, val in fm.items():
        if val:
            lines.append(f"{key}: {val}")
        else:
            lines.append(f"{key}:")
    lines.append("---")
    return "\n".join(lines) + "\n"


def load_skill(skill_name: str) -> str:
    """Load and truncate SKILL.md content for embedding. Includes version header."""
    skill_path = SKILLS_SRC / skill_name / "SKILL.md"
    if not skill_path.exists():
        return f"<!-- skill '{skill_name}' not found -->"

    raw = skill_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(raw)

    version = fm.get("version", "")
    version_comment = f"<!-- skill: {skill_name} v{version} -->\n" if version else ""

    if EMBED_END_MARKER in body:
        body = body[: body.index(EMBED_END_MARKER)]

    # Strip Changelog section from embedded content (it's metadata, not knowledge)
    changelog_idx = body.find("\n## Changelog")
    if changelog_idx != -1:
        body = body[:changelog_idx]

    lines = body.splitlines()
    if len(lines) > SKILL_EMBED_MAX_LINES:
        lines = lines[:SKILL_EMBED_MAX_LINES]
        lines.append(f"\n<!-- truncated — full skill at .agent/skills/{skill_name}/SKILL.md -->")

    return version_comment + "\n".join(lines).strip()


def parse_skills_list(value: str) -> list[str]:
    return [s.strip() for s in value.split(",") if s.strip()]


# ---------------------------------------------------------------------------
# Builders
# ---------------------------------------------------------------------------

def build_claude_agent(src_path: Path, is_workflow: bool = False) -> str:
    """Build .claude/agents/*.md content from a source .agent/agents/ or workflows/ file."""
    raw = src_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(raw)

    skills = parse_skills_list(fm.get("skills", ""))

    clean_fm: dict = {}
    clean_fm["name"] = fm.get("name", src_path.stem)

    desc = fm.get("description", "")
    if desc:
        clean_fm["description"] = desc

    tools = fm.get("tools", WORKFLOW_DEFAULT_TOOLS if is_workflow else "")
    if tools:
        clean_fm["tools"] = tools

    model = fm.get("model", "")
    if model and model != "inherit":
        clean_fm["model"] = model

    parts = [GENERATED_HEADER, render_frontmatter(clean_fm)]

    # For wf- agents: replace $ARGUMENTS with a note (subagents receive context differently)
    if is_workflow:
        body = body.replace(
            "$ARGUMENTS",
            "_Context from user message is passed automatically by Claude Code._",
        )

    parts.append(body)

    # Embed skills for specialist agents (Antigravity loads them dynamically; Claude Code needs inline)
    if skills and not is_workflow:
        parts.append("\n---\n\n## Embedded Skills\n")
        parts.append(
            "> Skills below are embedded from `.agent/skills/` for Claude Code compatibility.\n"
            "> Antigravity loads them dynamically via `skills:` frontmatter.\n"
        )
        for skill_name in skills:
            skill_content = load_skill(skill_name)
            parts.append(f"\n### Skill: `{skill_name}`\n\n{skill_content}\n")

    return "\n".join(parts)


def build_command(src_path: Path) -> str:
    """Build .claude/commands/<name>.md content from a .agent/workflows/ file.

    Keeps $ARGUMENTS verbatim — both Antigravity and Claude Code commands use the same syntax.
    Adds Claude Code-specific frontmatter (argument-hint, allowed-tools) on top of the
    original description field, without touching any Antigravity workflow content.
    """
    raw = src_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(raw)

    name = src_path.stem  # e.g. "debug", "architecture-bmad"
    meta = COMMAND_META.get(name, {})

    cmd_fm: dict = {}

    desc = fm.get("description", "")
    if desc:
        cmd_fm["description"] = desc

    hint = meta.get("argument-hint", "")
    if hint:
        cmd_fm["argument-hint"] = hint

    allowed = meta.get("allowed-tools", WORKFLOW_DEFAULT_TOOLS)
    cmd_fm["allowed-tools"] = allowed

    parts = [GENERATED_HEADER, render_frontmatter(cmd_fm)]
    parts.append(body)

    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Sync functions
# ---------------------------------------------------------------------------

def sync_agents(dry_run: bool = False, only_agent: str = "") -> None:
    CLAUDE_AGENTS_OUT.mkdir(parents=True, exist_ok=True)

    agent_files = sorted(AGENTS_SRC.glob("*.md"))
    if only_agent:
        agent_files = [f for f in agent_files if f.stem == only_agent]
        if not agent_files:
            print(f"ERROR: agent '{only_agent}' not found in {AGENTS_SRC}")
            sys.exit(1)

    print(f"\n=== Syncing specialist agents ({len(agent_files)}) ===")
    for src in agent_files:
        out_path = CLAUDE_AGENTS_OUT / src.name
        content = build_claude_agent(src, is_workflow=False)
        if dry_run:
            print(f"  [DRY] {out_path.relative_to(REPO_ROOT)}")
        else:
            out_path.write_text(content, encoding="utf-8")
            print(f"  ✓ {out_path.relative_to(REPO_ROOT)}")


def sync_workflows(dry_run: bool = False) -> None:
    CLAUDE_AGENTS_OUT.mkdir(parents=True, exist_ok=True)

    workflow_files = sorted(WORKFLOWS_SRC.glob("*.md"))
    print(f"\n=== Syncing workflow agents ({len(workflow_files)}) ===")
    for src in workflow_files:
        out_path = CLAUDE_AGENTS_OUT / f"wf-{src.name}"
        content = build_claude_agent(src, is_workflow=True)
        if dry_run:
            print(f"  [DRY] {out_path.relative_to(REPO_ROOT)}")
        else:
            out_path.write_text(content, encoding="utf-8")
            print(f"  ✓ {out_path.relative_to(REPO_ROOT)}")


def sync_commands(dry_run: bool = False) -> None:
    """Generate .claude/commands/ from .agent/workflows/.

    Each workflow becomes a /slash-command in Claude Code.
    $ARGUMENTS is preserved verbatim — compatible with both Antigravity and Claude Code.
    .agent/workflows/ files are never modified (Antigravity backward compatibility).
    """
    CLAUDE_COMMANDS_OUT.mkdir(parents=True, exist_ok=True)

    workflow_files = sorted(WORKFLOWS_SRC.glob("*.md"))
    print(f"\n=== Syncing slash commands ({len(workflow_files)}) ===")

    unknown = [f.stem for f in workflow_files if f.stem not in COMMAND_META]
    if unknown:
        print(f"  WARNING: no COMMAND_META entry for: {unknown}")
        print(f"  → These will use default tools: {WORKFLOW_DEFAULT_TOOLS}")

    for src in workflow_files:
        out_path = CLAUDE_COMMANDS_OUT / src.name
        content = build_command(src)
        if dry_run:
            print(f"  [DRY] {out_path.relative_to(REPO_ROOT)}")
        else:
            out_path.write_text(content, encoding="utf-8")
            print(f"  ✓ {out_path.relative_to(REPO_ROOT)}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(description="Sync .agent/ → .claude/agents/ and .claude/commands/")
    parser.add_argument("--dry-run", action="store_true", help="Print what would be written without writing")
    parser.add_argument("--agent", metavar="NAME", help="Sync only one specialist agent by name")
    parser.add_argument("--no-workflows", action="store_true", help="Skip wf- workflow agents in .claude/agents/")
    parser.add_argument("--no-commands", action="store_true", help="Skip slash commands in .claude/commands/")
    args = parser.parse_args()

    print(f"Repo root : {REPO_ROOT}")
    print(f"Agents out: {CLAUDE_AGENTS_OUT}")
    print(f"Commands  : {CLAUDE_COMMANDS_OUT}")

    sync_agents(dry_run=args.dry_run, only_agent=args.agent)

    if not args.agent:
        if not args.no_workflows:
            sync_workflows(dry_run=args.dry_run)
        if not args.no_commands:
            sync_commands(dry_run=args.dry_run)

    if not args.dry_run:
        n_agents   = len(list(CLAUDE_AGENTS_OUT.glob("*.md")))
        n_commands = len(list(CLAUDE_COMMANDS_OUT.glob("*.md")))
        print(f"\nDone. agents: {n_agents}  commands: {n_commands}")


if __name__ == "__main__":
    main()
