#!/usr/bin/env python3
"""Mechanized driver for a local-executor Arbor cycle.

Wraps the repetitive, purely-mechanical steps that were previously run by
hand as a dozen-plus separate `arbor_state.py`/`local_role_adapter.py`
invocations per cycle: session init, node creation, worktree creation,
dispatching the LOCAL executor, diff capture, recording scores, cleanup,
and reporting.

What this script deliberately does NOT do:

- IDEATE (deciding what candidates to try) - that requires judgment about
  the target file's actual weaknesses. Candidates are supplied as input
  (a JSON file of {parent_id, hypothesis, instructions, ...} objects), not
  generated by this script.
- JUDGE (scoring candidates) - local models were tested (2026-08-13) and do
  not discriminate reliably between weak and strong content (see
  .agent/skills/arbor-agent-executor/SKILL.md, "Local LLM Adapter Mode").
  Scoring must come from a Claude judge; feed the resulting scores back in
  via the `record` subcommand.

So the intended loop is:

    run_local_cycle.py init      --run-name R --task "..."
    run_local_cycle.py dispatch  --run-name R --candidates candidates.json
    # -> a Claude judge scores each experiments/<node>/diff.patch, produces scores.json
    run_local_cycle.py record    --run-name R --scores scores.json
    run_local_cycle.py finish    --run-name R --cleanup

candidates.json shape (a JSON list):
    [
      {
        "parent_id": "ROOT",
        "hypothesis": "Mechanism: ...\\nHypothesis: ...\\nObservable: ...\\nConflicts: ...",
        "target_file": ".agent/agents/qa/prompt-red-teamer.md",
        "instructions": "Rewrite ONLY the ... section. ...",
        "tier": "L4",                  # optional, else auto-detected from target_file frontmatter
        "model": null,                 # optional explicit override
        "require_prefix": "---",       # optional sanity check (whole-file mode only)
        "section_start": "## Some Heading",   # optional - switches to section-patch mode:
        "section_end": "## Next Heading"      # only this section is sent to/returned by the
                                               # model; everything else is preserved byte-for-
                                               # byte by this script. Strongly recommended for
                                               # large files. Omit section_end to patch to EOF.
      },
      ...
    ]

scores.json shape (a JSON object keyed by node id, as printed by `dispatch`):
    {
      "1": {"score": 87, "insight": "...", "result": "...", "merge": false},
      "2": {"score": 41, "insight": "...", "result": "...", "merge": false}
    }
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
ARBOR_STATE = SCRIPT_DIR / "arbor_state.py"
LOCAL_ADAPTER = SCRIPT_DIR / "local_role_adapter.py"

ADDED_NODE_RE = re.compile(r"^Added node (\S+)")
WORKTREE_KEY_ERR = "worktree command produced no parseable JSON"


def run(cmd: list[str], **kw) -> subprocess.CompletedProcess:
    kw.setdefault("capture_output", True)
    kw.setdefault("text", True)
    proc = subprocess.run(cmd, **kw)
    return proc


def arbor(cwd: Path, run_name: str, *args: str, check: bool = True) -> subprocess.CompletedProcess:
    cmd = ["python3", str(ARBOR_STATE), *args, "--cwd", str(cwd), "--run-name", run_name]
    proc = run(cmd)
    if check and proc.returncode != 0:
        raise SystemExit(f"arbor_state.py {args[0]} failed:\n{proc.stdout}\n{proc.stderr}")
    return proc


def cmd_init(args: argparse.Namespace) -> None:
    cwd = Path(args.cwd).resolve()
    proc = arbor(cwd, args.run_name, "init", "--task", args.task, "--max-depth", str(args.max_depth))
    print(proc.stdout.strip())
    meta_args = ["meta", "--set", "trunk_branch=main", "--set", "eval_cmd=NONE - Claude judge, no shell eval"]
    if args.dataset_info:
        meta_args += ["--set", f"dataset_info={args.dataset_info}"]
    arbor(cwd, args.run_name, *meta_args)
    print(f"session initialized: .arbor/sessions/{args.run_name}/")


def dispatch_one(cwd: Path, run_name: str, spec: dict[str, Any]) -> dict[str, Any]:
    parent_id = spec["parent_id"]
    hypothesis = spec["hypothesis"]
    target_file = spec["target_file"]

    add_proc = arbor(cwd, run_name, "add", "--parent-id", parent_id, "--hypothesis", hypothesis)
    m = ADDED_NODE_RE.search(add_proc.stdout.strip())
    if not m:
        return {"ok": False, "error": f"could not parse node id from: {add_proc.stdout!r}"}
    node_id = m.group(1)

    wt_proc = arbor(cwd, run_name, "worktree", "--node-id", node_id, "--trunk", "main")
    try:
        wt_info = json.loads(wt_proc.stdout.strip())
    except json.JSONDecodeError:
        return {"ok": False, "node_id": node_id, "error": WORKTREE_KEY_ERR}
    worktree = Path(wt_info["worktree"])
    branch = wt_info["branch"]

    arbor(cwd, run_name, "update", "--node-id", node_id, "--status", "running")

    exec_cmd = [
        "python3", str(LOCAL_ADAPTER), "executor",
        "--cwd", str(cwd),
        "--target-file", str(worktree / target_file),
        "--instructions", spec["instructions"],
        "--timeout", str(spec.get("timeout", 180)),
    ]
    if spec.get("model"):
        exec_cmd += ["--model", spec["model"]]
    elif spec.get("tier"):
        exec_cmd += ["--tier", spec["tier"]]
    if spec.get("require_prefix"):
        exec_cmd += [f"--require-prefix={spec['require_prefix']}"]
    if spec.get("section_start"):
        exec_cmd += [f"--section-start={spec['section_start']}"]
        if spec.get("section_end"):
            exec_cmd += [f"--section-end={spec['section_end']}"]

    exec_proc = run(exec_cmd)
    try:
        exec_result = json.loads(exec_proc.stdout.strip()) if exec_proc.stdout.strip() else {}
    except json.JSONDecodeError:
        exec_result = {}
    ok = exec_proc.returncode == 0 and exec_result.get("ok", False)

    result: dict[str, Any] = {
        "node_id": node_id,
        "ok": ok,
        "branch": branch,
        "worktree": str(worktree),
        "target_file": target_file,
        "model": exec_result.get("model"),
        "executor_stderr_tail": exec_proc.stderr[-500:] if not ok else None,
    }

    if ok:
        commit_msg = f"docs(agent): local-executor candidate for node {node_id}"
        run(["git", "-C", str(worktree), "add", target_file])
        commit = run(["git", "-C", str(worktree), "commit", "-m", commit_msg])
        if commit.returncode != 0 and "nothing to commit" not in commit.stdout:
            result["ok"] = False
            result["error"] = f"commit failed: {commit.stdout}{commit.stderr}"
            return result

        exp_dir = cwd / ".arbor" / "sessions" / run_name / "experiments" / node_id
        exp_dir.mkdir(parents=True, exist_ok=True)
        diff = run(["git", "-C", str(worktree), "diff", "main", "--", target_file])
        diff_path = exp_dir / "diff.patch"
        diff_path.write_text(diff.stdout, encoding="utf-8")
        result["diff_path"] = str(diff_path)
    else:
        arbor(cwd, run_name, "update", "--node-id", node_id, "--status", "pruned", check=False)
        result["insight_hint"] = "local executor failed require_prefix/empty-output check - escalate to a Claude executor for this node"

    return result


def cmd_dispatch(args: argparse.Namespace) -> None:
    cwd = Path(args.cwd).resolve()
    candidates = json.loads(Path(args.candidates).read_text(encoding="utf-8"))
    results = []
    for spec in candidates:
        # Tree-mutating arbor_state.py commands must run serially for the same run.
        results.append(dispatch_one(cwd, args.run_name, spec))
    print(json.dumps(results, indent=2))
    failed = [r for r in results if not r.get("ok")]
    if failed:
        print(f"\n{len(failed)}/{len(results)} candidate(s) need a Claude-executor fallback.", file=sys.stderr)


def cmd_record(args: argparse.Namespace) -> None:
    cwd = Path(args.cwd).resolve()
    scores = json.loads(Path(args.scores).read_text(encoding="utf-8"))
    for node_id, s in scores.items():
        arbor(
            cwd, args.run_name, "record",
            "--node-id", node_id,
            "--score", str(s["score"]),
            "--insight", s.get("insight", ""),
            "--result", s.get("result", ""),
            *(["--code-ref", s["code_ref"]] if s.get("code_ref") else []),
        )
    print(f"recorded {len(scores)} score(s)")


def cmd_finish(args: argparse.Namespace) -> None:
    cwd = Path(args.cwd).resolve()
    view = arbor(cwd, args.run_name, "view", "--format", "compact")
    print(view.stdout)
    arbor(cwd, args.run_name, "report")
    report_path = cwd / ".arbor" / "sessions" / args.run_name / "REPORT.md"
    print(f"report: {report_path}")

    if args.cleanup:
        tree = json.loads((cwd / ".arbor" / "sessions" / args.run_name / ".coordinator" / "idea_tree.json").read_text())
        wt_list = run(["git", "-C", str(cwd), "worktree", "list", "--porcelain"]).stdout
        branch_to_path = {}
        current_path = None
        for line in wt_list.splitlines():
            if line.startswith("worktree "):
                current_path = line.split(" ", 1)[1]
            elif line.startswith("branch ") and current_path:
                branch_to_path[line.split(" ", 1)[1].removeprefix("refs/heads/")] = current_path
        removed = 0
        for node in tree.get("nodes", {}).values():
            branch = node.get("code_ref")
            if branch and branch in branch_to_path:
                run(["git", "-C", str(cwd), "worktree", "remove", branch_to_path[branch], "--force"])
                run(["git", "-C", str(cwd), "branch", "-D", branch])
                removed += 1
        print(f"cleaned up {removed} worktree(s)/branch(es)")


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)

    sp = sub.add_parser("init")
    sp.add_argument("--cwd", default=".")
    sp.add_argument("--run-name", required=True)
    sp.add_argument("--task", required=True)
    sp.add_argument("--max-depth", type=int, default=2)
    sp.add_argument("--dataset-info", help="free-text metadata, e.g. 'target_file=...; merge_allowed=false'")
    sp.set_defaults(func=cmd_init)

    sp = sub.add_parser("dispatch")
    sp.add_argument("--cwd", default=".")
    sp.add_argument("--run-name", required=True)
    sp.add_argument("--candidates", required=True, help="path to a candidates.json (see module docstring)")
    sp.set_defaults(func=cmd_dispatch)

    sp = sub.add_parser("record")
    sp.add_argument("--cwd", default=".")
    sp.add_argument("--run-name", required=True)
    sp.add_argument("--scores", required=True, help="path to a scores.json (see module docstring)")
    sp.set_defaults(func=cmd_record)

    sp = sub.add_parser("finish")
    sp.add_argument("--cwd", default=".")
    sp.add_argument("--run-name", required=True)
    sp.add_argument("--cleanup", action="store_true", help="remove worktrees/branches for every node in the tree")
    sp.set_defaults(func=cmd_finish)

    return p


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    args.func(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
