#!/usr/bin/env python3
import unittest
import shutil
import sys
import json
from pathlib import Path
from unittest.mock import patch, MagicMock

# Antigravity Domain-Aware Import Logic
try:
    from lib.paths import REPO_ROOT
except ImportError:
    REPO_ROOT = Path(__file__).resolve().parents[3]
    sys.path.append(str(REPO_ROOT / ".agent" / "scripts"))
    for domain in ["health", "context", "delivery", "orchestration", "analysis", "models", "knowledge", "dev", "misc"]:
        sys.path.append(str(REPO_ROOT / ".agent" / "scripts" / domain))

import delivery.sync_agents as sync_agents

class TestSyncAgents(unittest.TestCase):
    def setUp(self):
        self.test_root = REPO_ROOT / "scratch" / "test_sync"
        if self.test_root.exists():
            shutil.rmtree(self.test_root)
        self.test_root.mkdir(parents=True)
        
        # Setup mock directory structure
        (self.test_root / ".agent" / "agents").mkdir(parents=True)
        (self.test_root / ".agent" / "workflows").mkdir(parents=True)
        (self.test_root / ".agent" / "skills").mkdir(parents=True)
        (self.test_root / ".agent" / "config").mkdir(parents=True)
        
        self.patch_repo = patch('delivery.sync_agents.REPO_ROOT', self.test_root)
        self.patch_source = patch('delivery.sync_agents.SOURCE_ROOT', self.test_root)
        self.patch_target = patch('delivery.sync_agents.TARGET_ROOT', self.test_root)
        
        # Important: Sync TARGETS paths to test_root
        sync_agents.TARGETS["claude"]["agents_out"] = self.test_root / ".claude" / "agents"
        sync_agents.TARGETS["claude"]["commands_out"] = self.test_root / ".claude" / "commands"
        sync_agents.TARGETS["opencode"]["agents_out"] = self.test_root / ".opencode" / "agents"
        sync_agents.TARGETS["opencode"]["commands_out"] = self.test_root / ".opencode" / "commands"
        sync_agents.TARGETS["opencode"]["config_out"] = self.test_root / "opencode.json"
        
        # Override source paths
        sync_agents.AGENTS_SRC = self.test_root / ".agent" / "agents"
        sync_agents.WORKFLOWS_SRC = self.test_root / ".agent" / "workflows"
        sync_agents.SKILLS_SRC = self.test_root / ".agent" / "skills"
        
        self.patch_repo.start()
        self.patch_source.start()
        self.patch_target.start()

    def tearDown(self):
        self.patch_repo.stop()
        self.patch_source.stop()
        self.patch_target.stop()
        if self.test_root.exists():
            shutil.rmtree(self.test_root)

    def test_parse_frontmatter(self):
        content = "---\nname: Test\n---\nBody"
        fm, body = sync_agents.parse_frontmatter(content)
        self.assertEqual(fm["name"], "Test")
        self.assertEqual(body.strip(), "Body")

    def test_build_agent_file_claude(self):
        src = self.test_root / ".agent" / "agents" / "tester.md"
        src.write_text("---\nskills: testing\n---\nHello")
        
        # Mock skill existence
        (self.test_root / ".agent" / "skills" / "testing").mkdir(parents=True)
        (self.test_root / ".agent" / "skills" / "testing" / "SKILL.md").write_text("Skill Content")
        
        out = sync_agents.build_agent_file(src, "claude")
        self.assertIn("GENERATED by sync_agents.py", out)
        self.assertIn(".agent/skills/testing/SKILL.md", out)

    def test_sync_mcp_config_opencode(self):
        mcp_src = self.test_root / ".agent" / "config" / "mcp_config.json"
        mcp_src.write_text(json.dumps({
            "mcpServers": {
                "test-server": {
                    "command": "node",
                    "args": ["server.js"],
                    "enabled": True
                }
            }
        }))
        
        sync_agents.sync_mcp_config("opencode", dry_run=False, check=False)
        
        dest = self.test_root / "opencode.json"
        self.assertTrue(dest.exists())
        data = json.loads(dest.read_text())
        self.assertEqual(data["mcp"]["test-server"]["command"], ["node", "server.js"])

    def test_sync_full_opencode(self):
        (self.test_root / ".agent" / "agents" / "dev.md").write_text("---\ndomains: dev\n---\nDev body")
        
        sync_agents.sync("opencode")
        
        out_agent = self.test_root / ".opencode" / "agents" / "dev.md"
        self.assertTrue(out_agent.exists())
        self.assertIn("Dev body", out_agent.read_text())

if __name__ == "__main__":
    unittest.main()
