#!/usr/bin/env python3
"""
sync_agents.py — Generate .claude/ and .opencode/ agent layers from .agent/

This script universalizes the agent infrastructure by syncing the source of truth (.agent/)
to client-specific directories (.claude/ for Claude Code, .opencode/ for OpenCode).

Usage:
    python3 .agent/scripts/delivery/sync_agents.py --target claude
    python3 .agent/scripts/delivery/sync_agents.py --target opencode
"""

# Antigravity Domain-Aware Import Logic
try:
    from lib.paths import REPO_ROOT
except ImportError:
    import sys
    from pathlib import Path
    SCRIPTS_DIR = Path(__file__).resolve().parents[1]
    if str(SCRIPTS_DIR) not in sys.path:
        sys.path.append(str(SCRIPTS_DIR))
    for domain in ["health", "context", "delivery", "orchestration", "analysis", "models", "knowledge", "dev"]:
        d_path = str(SCRIPTS_DIR / domain)
        if d_path not in sys.path:
            sys.path.append(d_path)


import argparse
import sys
import os
import json
import logging
import re
from pathlib import Path

from lib.suppress import suppress
from lib.common import get_timestamp, validate_json

REPO_ROOT = Path(__file__).parent.parent.parent.parent.resolve()
SOURCE_ROOT = REPO_ROOT
TARGET_ROOT = REPO_ROOT

AGENTS_SRC    = SOURCE_ROOT / ".agent" / "agents"
WORKFLOWS_SRC = SOURCE_ROOT / ".agent" / "workflows"
SKILLS_SRC    = SOURCE_ROOT / ".agent" / "skills"

# Targets Configuration
TARGETS = {
    "claude": {
        "agents_out":   TARGET_ROOT / ".claude" / "agents",
        "commands_out": TARGET_ROOT / ".claude" / "commands",
        "skills_out":   TARGET_ROOT / ".claude" / "skills",
        "header": "<!-- GENERATED by sync_agents.py (target: claude) — do not edit directly -->\n",
        "workflow_prefix": "wf-",
    },
    "opencode": {
        "agents_out":   TARGET_ROOT / ".opencode" / "agents",
        "commands_out": TARGET_ROOT / ".opencode" / "commands",
        "skills_out":   TARGET_ROOT / ".opencode" / "skills",
        "config_out":   TARGET_ROOT / "opencode.json",
        "header": "<!-- GENERATED by sync_agents.py (target: opencode) — do not edit directly -->\n",
        "workflow_prefix": "", # OpenCode prefers direct names or categories
    }
}

WORKFLOW_DEFAULT_TOOLS = "Read, Grep, Glob, Bash, Write, Edit"

AGENT_DEFAULT_TOOLS: dict[str, str] = {
    "orchestrator":           "Read, Write, Edit, Bash, Grep, Glob, Agent",
    "analyst":                "Read, Write, Edit, Grep, Glob, Agent",
    "project-planner":        "Read, Write, Edit, Grep, Glob, Agent",
    "ai-engineer":            "Read, Write, Edit, Bash, Grep, Glob, Agent",
    "backend-specialist":     "Read, Write, Edit, Bash, Grep, Glob",
    "frontend-specialist":    "Read, Write, Edit, Bash, Grep, Glob",
    "crypto-go-architect":   "Read, Write, Edit, Bash, Grep, Glob",
    "database-architect":     "Read, Write, Edit, Bash, Grep, Glob",
    "mobile-developer":       "Read, Write, Edit, Bash, Grep, Glob",
    "game-developer":         "Read, Write, Edit, Bash, Grep, Glob",
    "devops-engineer":        "Read, Write, Edit, Bash, Grep, Glob",
    "k8s-engineer":           "Read, Write, Edit, Bash, Grep, Glob",
    "data-engineer":          "Read, Write, Edit, Bash, Grep, Glob",
    "grpc-architect":         "Read, Write, Edit, Bash, Grep, Glob",
    "test-engineer":          "Read, Write, Edit, Bash, Grep, Glob",
    "qa-automation-engineer": "Read, Write, Edit, Bash, Grep, Glob",
    "code-archaeologist":     "Read, Write, Edit, Bash, Grep, Glob",
    "debugger":               "Read, Bash, Grep, Glob",
    "performance-optimizer":  "Read, Bash, Grep, Glob, Write",
    "security-auditor":       "Read, Bash, Grep, Glob",
    "penetration-tester":     "Read, Bash, Grep, Glob",
    "explorer-agent":         "Read, Bash, Grep, Glob",
    "git-master":             "Read, Bash, Grep, Glob",
    "reviewer":               "Read, Bash, Grep, Glob, Write",
    "documentation-writer":   "Read, Write, Edit, Grep, Glob",
    "wiki-architect":         "Read, Write, Edit, Grep, Glob",
    "rest-api-designer":      "Read, Write, Edit, Grep, Glob",
    "seo-specialist":         "Read, Write, Grep, Glob",
    "product-manager":        "Read, Write, Grep, Glob",
    "product-owner":          "Read, Write, Grep, Glob",
    "python-specialist":      "Read, Write, Edit, Bash, Grep, Glob",
    # Previously using workflow defaults — now explicit.
    # Note: agents with 'tools:' in their source frontmatter use that value;
    # entries here apply only when frontmatter has no tools field.
    "archivist":              "Read, Write, Edit, Grep, Glob, Bash",
    "chaos-monkey":           "Read, Bash, Grep, Glob",
    "cto":                    "Read, Write, Edit, Grep, Glob, Agent",
    "ethics-auditor":         "Read, Grep, Glob",
    "maintainer":             "Read, Write, Edit, Bash, Grep, Glob",
    "red-team":               "Read, Bash, Grep, Glob",
    "release-manager":        "Read, Write, Edit, Bash, Grep, Glob",
    "risk-manager":           "Read, Write, Edit, Grep, Glob",
    "visual-designer":        "Read, Write, Grep, Glob",
    # cloud-engineer, crypto-specialist, go-specialist, grafana-master,
    # paperclip, prompt-specialist, sre-engineer — tools defined in frontmatter
}

COMMAND_META: dict[str, dict] = {
    "debug": {
        "argument-hint": "<error or issue description>",
        "allowed-tools": "Read, Grep, Glob, Bash",
    },
    "plan": {
        "argument-hint": "<feature or task to plan>",
        "allowed-tools": "Read, Grep, Glob, Write",
    },
    "create": {
        "argument-hint": "<app description, e.g. todo app with auth>",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit, Agent",
    },
    "deploy": {
        "argument-hint": "[environment: staging|production]",
        "allowed-tools": "Read, Bash",
    },
    "enhance": {
        "argument-hint": "<feature or improvement description>",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit",
    },
    "orchestrate": {
        "argument-hint": "<complex multi-domain task>",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit, Agent",
    },
    "status": {
        "argument-hint": "",
        "allowed-tools": "Read, Grep, Bash",
    },
    "dag-run": {
        "argument-hint": "",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit",
    },
}

# Skills injected by the sync script into agent files (in addition to frontmatter skills).
# Covers the 31 skills that exist in .agent/skills/ but are not referenced in any agent .md.
AGENT_SKILL_EXTRAS: dict[str, list[str]] = {
    "orchestrator":           ["dispatching-parallel-agents", "agent-routing-pro"],
    "ai-engineer":            ["mcp-integration", "hook-development", "skill-creator",
                               "agent-development", "command-development"],
    "backend-specialist":     ["api-development", "postgres-best-practices", "typed-service-contracts",
                               "better-auth-best-practices", "convex-setup-auth", "paperclip-worker"],
    "frontend-specialist":    ["shadcn-best-practices", "next-best-practices", "ui-ux-pro-max",
                               "browser-use", "playwright-best-practices",
                               "better-auth-best-practices", "paperclip-worker"],
    "mobile-developer":       ["paperclip-worker"],
    "go-specialist":          ["paperclip-worker"],
    "test-engineer":          ["test-driven-development", "verification-before-completion"],
    "qa-automation-engineer": ["playwright-best-practices", "browser-use", "agent-browser"],
    "devops-engineer":        ["github-actions-expert", "sentry-cli-expert"],
    "sre-engineer":           ["sentry-cli-expert"],
    "database-architect":     ["postgres-best-practices", "turso-db", "supabase-postgres-best-practices"],
    "data-engineer":          ["nextflow-development"],
    "archivist":              ["semantic-search"],
    "reviewer":               ["verification-before-completion", "requesting-code-review"],
    "prompt-specialist":      ["prompts-best-practices", "skill-creator",
                               "agent-development", "command-development"],
    "visual-designer":        ["visual-explainer"],
    "analyst":                ["scientific-problem-selection"],
}

# Read-only Bash and MCP operations that should not prompt the user each time.
CLAUDE_PERMISSIONS_ALLOW = [
    "Bash(git status)",
    "Bash(git log*)",
    "Bash(git diff*)",
    "Bash(git branch*)",
    "Bash(ls*)",
    "Bash(find . *)",
    "Bash(python3 .agent/scripts/health/status_report.py)",
    "Bash(python3 .agent/scripts/delivery/sync_agents.py --check*)",
    "Bash(python3 .agent/scripts/dev/checklist.py*)",
    "mcp__local-skill-server__*",
    "mcp__github__get_*",
    "mcp__github__list_*",
    "mcp__github__search_*",
    "mcp__filesystem__read_*",
    "mcp__filesystem__list_*",
    "mcp__wikipedia__*",
]

# Inline guardrail command — kept here so settings.json can be fully generated.
_GUARDRAIL_CMD = (
    "python3 -c \"\n"
    "import json, sys, subprocess, os\n"
    "data = json.load(sys.stdin)\n"
    "cmd = data.get('tool_input', {}).get('command', '')\n"
    "if not cmd:\n"
    "    sys.exit(0)\n"
    "# Walk up to find the project root (contains .agent/scripts/guardrail_monitor.py)\n"
    "root = os.getcwd()\n"
    "for _ in range(6):\n"
    "    script = os.path.join(root, '.agent/scripts/health/guardrail_monitor.py')\n"
    "    if os.path.isfile(script):\n"
    "        break\n"
    "    parent = os.path.dirname(root)\n"
    "    if parent == root:\n"
    "        script = None\n"
    "        break\n"
    "    root = parent\n"
    "else:\n"
    "    script = None\n"
    "if not script:\n"
    "    sys.exit(0)\n"
    "result = subprocess.run(\n"
    "    ['python3', script, '--check-cmd', cmd],\n"
    "    capture_output=True, text=True\n"
    ")\n"
    "if result.returncode == 2:\n"
    "    print(result.stdout.strip())\n"
    "    sys.exit(2)\n"
    "sys.exit(0)\n"
    "\""
)

CLAUDE_KEYBINDINGS = [
    {"key": "ctrl+shift+o", "command": "/orchestrate"},
    {"key": "ctrl+shift+d", "command": "/debug"},
    {"key": "ctrl+shift+s", "command": "/status"},
    {"key": "ctrl+shift+r", "command": "/reviewer"},
    {"key": "ctrl+shift+t", "command": "/test"},
    {"key": "ctrl+shift+c", "command": "/create"},
    {"key": "ctrl+shift+g", "command": "/dag-run"},
]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def parse_frontmatter(content: str) -> tuple[dict, str]:
    if not content.startswith("---"):
        return {}, content
    end = content.find("\n---", 3)
    if end == -1:
        return {}, content
    fm_block = content[3:end].strip()
    body = content[end + 4:].lstrip("\n")
    frontmatter: dict = {}
    for line in fm_block.splitlines():
        if ":" in line:
            key, _, val = line.partition(":")
            frontmatter[key.strip()] = val.strip()
    return frontmatter, body

def render_frontmatter(fm: dict) -> str:
    lines = ["---"]
    for key, val in fm.items():
        if val: lines.append(f"{key}: {val}")
        else: lines.append(f"{key}:")
    lines.append("---")
    return "\n".join(lines) + "\n"

def skill_exists(skill_name: str) -> bool:
    return (SKILLS_SRC / skill_name / "SKILL.md").exists()

# ---------------------------------------------------------------------------
# Builders
# ---------------------------------------------------------------------------

def build_agent_file(src_path: Path, target: str, is_workflow: bool = False) -> str:
    raw = src_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(raw)
    agent_name = src_path.stem
    skills_raw = fm.get("skills", "") or ""
    skills_clean = str(skills_raw).strip().strip("[]").strip()
    skills = [s.strip() for s in skills_clean.split(",") if s.strip()]

    clean_fm: dict = {}
    clean_fm["name"] = fm.get("name", agent_name)
    if fm.get("description"): clean_fm["description"] = fm["description"]

    # Target specific logic
    if target == "claude":
        clean_fm["tools"] = fm.get("tools") or AGENT_DEFAULT_TOOLS.get(agent_name) or WORKFLOW_DEFAULT_TOOLS
    elif target == "opencode":
        # OpenCode might use standard frontmatter
        if fm.get("model"): clean_fm["model"] = fm["model"]

    parts = [TARGETS[target]["header"], render_frontmatter(clean_fm)]
    
    if is_workflow and target == "claude":
        body = body.replace("$ARGUMENTS", "_Context from user message is passed automatically by Claude Code._")
    
    parts.append(body)

    if target == "claude" and not is_workflow:
        extras = AGENT_SKILL_EXTRAS.get(agent_name, [])
        all_skills = list(dict.fromkeys(skills + extras))  # merge, dedup, preserve order
        skill_lines = "\n".join(f"- `.agent/skills/{s}/SKILL.md`" for s in all_skills if skill_exists(s))
        if skill_lines:
            parts.append("\n---\n\n> **Skills** — read these files with the `Read` tool before starting:\n" + skill_lines + "\n")

    return "\n".join(parts)

def build_command_file(src_path: Path, target: str) -> str:
    raw = src_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(raw)
    name = src_path.stem
    meta = COMMAND_META.get(name, {})

    cmd_fm: dict = {}
    if fm.get("description"): cmd_fm["description"] = fm["description"]

    if target == "claude":
        cmd_fm["argument-hint"] = meta.get("argument-hint", "")
        cmd_fm["allowed-tools"] = meta.get("allowed-tools", WORKFLOW_DEFAULT_TOOLS)
    elif target == "opencode":
        # OpenCode commands often specify an agent or mode
        cmd_fm["agent"] = fm.get("agent", "orchestrator")
        if meta.get("argument-hint"):
            body = f"> Hint: {meta['argument-hint']}\n\n" + body

    parts = [TARGETS[target]["header"], render_frontmatter(cmd_fm), body]
    return "\n".join(parts)

# ---------------------------------------------------------------------------
# Sync Logic
# ---------------------------------------------------------------------------

def cleanup_orphans(target: str, expected_files: set, dry_run: bool):
    config = TARGETS[target]
    for out_dir in [config["agents_out"], config["commands_out"]]:
        if not out_dir.exists():
            continue
        for item in out_dir.glob("*.md"):
            if item not in expected_files:
                rel = item.relative_to(TARGET_ROOT)
                if dry_run:
                    print(f"  [ORPHAN-DRY] {rel}")
                else:
                    item.unlink()
                    print(f"  🗑️ {rel}")

def get_profile_extra_agents(profile_name: str) -> set:
    if not profile_name:
        return set()
    profile_path = REPO_ROOT / ".github" / "profiles.yml"
    if not profile_path.exists():
        return set()
    try:
        import yaml
        with open(profile_path) as f:
            data = yaml.safe_load(f)
            return set(data.get("profiles", {}).get(profile_name, {}).get("extra_agents", []))
    except Exception:
        return set()

def should_include_agent(src: Path, profile_name: str, extra_agents: set) -> bool:
    if not profile_name:
        return True
    if src.stem in extra_agents:
        return True
    
    # Check frontmatter
    content = src.read_text()
    if not content.startswith("---"):
        return True # Universal if no frontmatter

    # Bound on a line-anchored "\n---" (matches parse_frontmatter()'s own
    # boundary logic), not a blind content.split("---", 2) — a bare substring
    # split breaks the moment the frontmatter body contains "---" anywhere
    # earlier, e.g. a YAML comment like "# --- Squad Leads --- " inside a
    # delegates_to list (real example: cto.md — this silently truncated the
    # parse right after `hierarchy:`, dropping the real `profile:` field and
    # making the agent look profile-universal regardless of what it declared).
    end = content.find("\n---", 3)
    if end == -1:
        return True
    fm_block = content[3:end]

    try:
        import yaml
        fm = yaml.safe_load(fm_block)
        agent_profiles = fm.get("profile", "")
        if not agent_profiles:
            return True # Universal
        
        allowed = [p.strip() for p in str(agent_profiles).split(",")]
        return profile_name in allowed
    except Exception:
        return True # Fallback to include

def sync_mcp_config(target: str, dry_run: bool, check: bool):
    if target != "opencode":
        return # Claude uses symlinks or global config
    
    src_path = SOURCE_ROOT / ".agent" / "config" / "mcp_config.json"
    dest_path = TARGETS[target].get("config_out")
    
    if not src_path.exists() or not dest_path:
        return

    import json
    try:
        with open(src_path, "r") as f:
            src_data = json.load(f)
        
        # Always use the latest instructions and permissions from the hub template
        base_template = {
            "$schema": "https://opencode.ai/config.json",
            "default_agent": "orchestrator",
            "instructions": [
                ".agent/rules/gemini/00_protocol.md",
                ".agent/rules/gemini/01_classifier.md"
            ],
            "permission": {
                "shell": "allow",
                "file": "allow",
                "network": "allow"
            },
            "mcp": {}
        }

        if dest_path.exists():
            with open(dest_path, "r") as f:
                dest_data = json.load(f)
            # Provisioning: Always overwrite core sections from hub
            dest_data["instructions"] = base_template["instructions"]
            dest_data["permission"] = base_template["permission"]
            dest_data["$schema"] = base_template["$schema"]
            dest_data["default_agent"] = base_template["default_agent"]
        else:
            dest_data = base_template
        
        mcp_servers = src_data.get("mcpServers", {})
        converted = {}
        
        for name, cfg in mcp_servers.items():
            # Convert Claude style to OpenCode style
            cmd_array = [cfg.get("command", "")]
            cmd_array.extend(cfg.get("args", []))
            
            converted[name] = {
                "type": "local",
                "command": [c for c in cmd_array if c],
                "enabled": cfg.get("enabled", True),
                "env": cfg.get("env", {})
            }
        
        dest_data["mcp"] = converted

        # Auto-generate agent section from .agent/agents/
        if target == "opencode":
            # Collect all agent names first for router-rules loading
            all_agent_names = _collect_agent_names()
            _ensure_router_rules_loaded(all_agent_names)

            agent_configs = _build_agent_section()
            if agent_configs:
                # Add model assignments based on agent tier (from router_rules.json)
                for agent_name in agent_configs:
                    agent_configs[agent_name]["model"] = _get_agent_model(agent_name)
                dest_data["agent"] = agent_configs
                print(f"  🤖 Agents: {len(agent_configs)} subagents configured for task()")

            # Auto-generate provider section (MCP LLM Broker HTTP API)
            provider_config = _build_provider_section()
            if provider_config:
                dest_data["provider"] = provider_config
                print(f"  🔌 Provider: mcp-llm-broker ({len(provider_config.get('mcp-llm-broker', {}).get('models', {}))} models)")
        
        new_content = json.dumps(dest_data, indent=2) + "\n"
        
        if check:
            if not dest_path.exists():
                print(f"  [MISSING] {dest_path.relative_to(TARGET_ROOT)}")
                sys.exit(1)
            existing = dest_path.read_text()
            if existing.strip() != new_content.strip():
                print(f"  [DRIFT] {dest_path.relative_to(TARGET_ROOT)}")
                sys.exit(1)
            return

        if not dry_run:
            dest_path.write_text(new_content)
            print(f"  ✓ {dest_path.relative_to(TARGET_ROOT)} (MCP Synced)")
        else:
            print(f"  [DRY] {dest_path.relative_to(TARGET_ROOT)} (MCP Sync)")
            
    except Exception as e:
        print(f"  ⚠️ Failed to sync MCP config: {e}")



def _parse_frontmatter_yaml(content: str) -> dict:
    """Full YAML frontmatter parse — preserves nested structures (hierarchy,
    delegates_to lists, etc.) that the lightweight line-splitting
    parse_frontmatter() above intentionally flattens/loses.

    Bounds the frontmatter block the same way parse_frontmatter() does —
    content.find("\\n---", 3), i.e. the closing delimiter must be a line
    starting at column 0 — rather than a blind content.split("---", 2). A
    naive split breaks the instant the frontmatter body contains the bare
    substring "---" anywhere earlier, e.g. a YAML comment like
    "# --- Squad Leads --- " inside a delegates_to list (real example: this
    silently truncated cto.md's parsed frontmatter right after `hierarchy:`,
    dropping skills/domains/tools/profile/model — a comment mid-list starting
    with whitespace, not column 0, doesn't trip the "\\n---" anchor).

    Used only for the agent registry manifest: downstream consumers (this
    broker, and external consumers like multica) need the complete frontmatter,
    not just name/description.
    """
    if not content.startswith("---"):
        return {}
    end = content.find("\n---", 3)
    if end == -1:
        return {}
    fm_block = content[3:end]
    try:
        import yaml
        fm = yaml.safe_load(fm_block)
        return fm if isinstance(fm, dict) else {}
    except Exception as e:
        logging.warning("Failed to YAML-parse frontmatter: %s", e)
        return {}


def build_agent_registry(agent_files: list) -> tuple[bool, dict]:
    """Build the in-memory, schema-validated agent index from already-filtered
    agent source files. Not persisted anywhere — see validate_agent_registry().

    Each entry is the agent's full frontmatter as-is (name, description, model,
    domains, skills, hierarchy, ...) — no fixed field list, so any consumer
    that reads this in-process list gets whatever fields an agent declares;
    only name/description are contractually required (see the schema).

    `agent_files` is the same profile-filtered list `sync()` already used to write
    `.claude/agents/` — this must never include an agent whose .md file wasn't
    actually synced for this run.

    An earlier design read the Agents table out of ARCHITECTURE.md at broker
    runtime as the call_agent registry — that table silently dropped any agent
    added without a matching row (see
    tasks/2026-07-25-mcp-llm-broker-call-agent-drops-management-tier-agents.md).
    A second design persisted this same data as a compiled
    .agent/config/agent_registry.json manifest for the broker to read instead
    of scanning live — that manifest was removed: mcp-llm-broker's
    loadAgentList() now scans .agent/agents/**/*.md directly at request time
    (matching how invokeAgent already read a single agent's file), and this
    function's only remaining job is the CI-time schema check below, plus
    feeding ARCHITECTURE.md's auto-generated table.

    Returns (ok, data). `ok` is False when schema validation fails — callers must
    treat that as a hard error and exit non-zero (CI gate) rather than let a
    malformed agent's frontmatter go unnoticed.
    """
    agents = []
    for src in agent_files:
        content = src.read_text(encoding="utf-8")
        fm = _parse_frontmatter_yaml(content)
        entry = dict(fm)
        entry.setdefault("name", src.stem)
        entry.setdefault("description", "")
        agents.append(entry)
    agents.sort(key=lambda a: str(a.get("name", "")))

    data = {"generated_at": get_timestamp(), "agents": agents}
    schema_path = SOURCE_ROOT / ".agent" / "config" / "agent_registry.schema.json"
    ok, msg = validate_json(data, schema_path)
    if not ok:
        print(f"  ❌ agent frontmatter failed schema validation: {msg}")
    return ok, data


def validate_agent_registry(agent_files: list) -> list:
    """CI gate: build the agent index and hard-fail (sys.exit(1)) on any
    schema violation — an agent missing a required field (name/description)
    must break the build, not silently ship.

    Returns the agent entry list (in-memory only — nothing is written to
    disk) so sync_architecture_md() can render ARCHITECTURE.md's table from
    the exact same validated build instead of re-scanning the filesystem.
    """
    ok, data = build_agent_registry(agent_files)
    if not ok:
        sys.exit(1)
    return data["agents"]


def _first_sentence(text: str, max_len: int = 90) -> str:
    """Best-effort short summary for ARCHITECTURE.md's Focus column — full
    descriptions run multiple sentences and would make the table unreadable."""
    text = (text or "").strip()
    if not text:
        return ""
    for sep in (". ", "! ", "? "):
        idx = text.find(sep)
        if 0 < idx <= max_len:
            return text[: idx + 1].strip()
    return (text[:max_len].rstrip() + "…") if len(text) > max_len else text


def build_architecture_agents_table(agents: list) -> str:
    """Render the '## 🤖 Agents' section of ARCHITECTURE.md from the same data
    as agent_registry.json — replaces hand-maintenance of this table, which was
    the root cause of tasks/2026-07-25-mcp-llm-broker-call-agent-drops-management-tier-agents.md
    (a manually-added agent with no matching row silently became uncallable).
    """
    orchestrator = next((a for a in agents if a.get("name") == "orchestrator"), None)
    rest = sorted(
        (a for a in agents if a.get("name") != "orchestrator"),
        key=lambda a: str(a.get("name", "")),
    )
    ordered = ([orchestrator] if orchestrator else []) + rest

    lines = [
        f"## 🤖 Agents ({len(agents)})",
        "",
        "Specialist AI personas for different domains.",
        "",
        "<!-- GENERATED by sync_agents.py — do not edit directly. Regenerate with:",
        "     python3 .agent/scripts/delivery/sync_agents.py --target claude -->",
        "",
        "| Agent | Focus | Skills Used |",
        "| --- | --- | --- |",
    ]
    for a in ordered:
        name = a.get("name", "")
        focus = _first_sentence(a.get("description", ""))
        skills_raw = a.get("skills", "")
        if isinstance(skills_raw, list):
            skills = ", ".join(str(s) for s in skills_raw)
        else:
            skills = str(skills_raw or "")
        lines.append(f"| `{name}` | {focus} | {skills} |")

    return "\n".join(lines) + "\n"


SKILL_SKIP_DIRS = {"archive", "scratch"}


def build_architecture_skills_table() -> str:
    """Render the '## 🧩 Skills' section of ARCHITECTURE.md straight off the
    .agent/skills/ directory — replaces hand-maintenance of this table, which
    drifted the same way the Agents table did (see build_architecture_agents_table):
    a hand-written count ('118 Skills' vs a '(67)' header vs ~163 actual dirs)
    and a category breakdown covering a fraction of real skills.
    """
    rows = []
    for skill_md in sorted(SKILLS_SRC.glob("*/SKILL.md")):
        skill_dir = skill_md.parent
        if skill_dir.name in SKILL_SKIP_DIRS:
            continue
        fm, _ = parse_frontmatter(skill_md.read_text(encoding="utf-8"))
        desc = _first_sentence(fm.get("description", "").strip('"\''))
        rows.append((skill_dir.name, desc))

    lines = [
        f"## 🧩 Skills ({len(rows)})",
        "",
        "Modular knowledge domains that agents can load on-demand, based on task context.",
        "",
        "<!-- GENERATED by sync_agents.py — do not edit directly. Regenerate with:",
        "     python3 .agent/scripts/delivery/sync_agents.py --target claude -->",
        "",
        "| Skill | Description |",
        "| --- | --- |",
    ]
    for name, desc in rows:
        lines.append(f"| `{name}` | {desc} |")

    return "\n".join(lines) + "\n"


def _replace_architecture_section(path: Path, header_prefixes: tuple, new_block: str, dry_run: bool, check: bool) -> bool:
    """Rewrite a single '## ...' section of ARCHITECTURE.md in place (matched
    by header_prefixes), leaving every other section untouched. Returns False
    (no-op) if the file or the target section doesn't exist.
    """
    if not path.exists():
        return False

    lines = path.read_text(encoding="utf-8").split("\n")

    start = None
    end = len(lines)
    for i, line in enumerate(lines):
        if start is None and line.startswith(header_prefixes):
            start = i
            continue
        if start is not None and i > start and line.startswith("## "):
            end = i
            break

    if start is None:
        return False

    new_lines = lines[:start] + new_block.rstrip("\n").split("\n") + [""] + lines[end:]
    new_content = "\n".join(new_lines)
    if not new_content.endswith("\n"):
        new_content += "\n"

    _write(path, new_content, dry_run, check)
    return True


def _sync_overview_counts(path: Path, agent_count: int, skill_count: int, dry_run: bool, check: bool):
    """Keep the '## 📋 Overview' bullet counts (Agents/Skills/Workflows) from
    drifting out of sync with the tables further down — same drift class as
    the tables themselves, just a different spot in the file.
    """
    if not path.exists():
        return
    workflow_count = len(list(WORKFLOWS_SRC.glob("*.md")))
    content = path.read_text(encoding="utf-8")
    new_content = content
    new_content = re.sub(r"-\s*\*\*\d+\s+Specialist Agents\*\*", f"- **{agent_count} Specialist Agents**", new_content, count=1)
    new_content = re.sub(r"-\s*\*\*\d+\s+Skills\*\*", f"- **{skill_count} Skills**", new_content, count=1)
    new_content = re.sub(r"-\s*\*\*\d+\s+Workflows\*\*", f"- **{workflow_count} Workflows**", new_content, count=1)
    if new_content != content:
        _write(path, new_content, dry_run, check)


def sync_architecture_md(agents: list, dry_run: bool, check: bool):
    """Rewrite the '## 🤖 Agents' and '## 🧩 Skills' sections of ARCHITECTURE.md
    in place, leaving every other section untouched. No-op if ARCHITECTURE.md
    doesn't exist at the target (e.g. a consumer repo that doesn't ship it).
    """
    path = TARGET_ROOT / ".agent" / "ARCHITECTURE.md"
    if not path.exists():
        return

    if not _replace_architecture_section(path, ("## 🤖 Agents", "## Agents ("), build_architecture_agents_table(agents), dry_run, check):
        logging.warning("ARCHITECTURE.md has no '## 🤖 Agents' section — skipping table regeneration")

    skills_table = build_architecture_skills_table()
    if not _replace_architecture_section(path, ("## 🧩 Skills", "## Skills ("), skills_table, dry_run, check):
        logging.warning("ARCHITECTURE.md has no '## 🧩 Skills' section — skipping table regeneration")

    skill_count = int(re.match(r"## 🧩 Skills \((\d+)\)", skills_table.split("\n", 1)[0]).group(1))
    _sync_overview_counts(path, len(agents), skill_count, dry_run, check)


def sync(target: str, dry_run: bool = False, check: bool = False, only_agent: str = "", profile: str = "", no_commands: bool = False, no_workflows: bool = False):
    config = TARGETS[target]
    config["agents_out"].mkdir(parents=True, exist_ok=True)
    config["commands_out"].mkdir(parents=True, exist_ok=True)

    print(f"\n=== Syncing TARGET: {target} ===")
    print(f"  Source: {SOURCE_ROOT}")
    print(f"  Target: {TARGET_ROOT}")
    
    expected_files = set()
    extra_agents = get_profile_extra_agents(profile)

    # 1. Specialist Agents
    agent_files = sorted(AGENTS_SRC.rglob("**/*.md"))
    if only_agent:
        agent_files = [f for f in agent_files if f.stem == only_agent]

    included_agent_files = []
    for src in agent_files:
        if not should_include_agent(src, profile, extra_agents):
            continue

        included_agent_files.append(src)
        out_path = config["agents_out"] / src.name
        expected_files.add(out_path)
        content = build_agent_file(src, target, is_workflow=False)
        _write(out_path, content, dry_run, check)

    # 1.5 Agent frontmatter CI gate + ARCHITECTURE.md's Agents table — both
    # derived from the same in-memory validated build, target-independent,
    # run once from the claude-target sync. No manifest file is written;
    # mcp-llm-broker scans .agent/agents/**/*.md directly at request time.
    if target == "claude" and not only_agent:
        validated_agents = validate_agent_registry(included_agent_files)
        sync_architecture_md(validated_agents, dry_run, check)

    # 2. Workflows as Agents (Claude only usually)
    if target == "claude" and not no_workflows:
        for src in sorted(WORKFLOWS_SRC.glob("*.md")):
            # Workflows are generally universal unless we add profile support for them too
            out_path = config["agents_out"] / f"wf-{src.name}"
            expected_files.add(out_path)
            content = build_agent_file(src, target, is_workflow=True)
            _write(out_path, content, dry_run, check)

    # 3. Workflows as Commands
    if not no_commands:
        for src in sorted(WORKFLOWS_SRC.glob("*.md")):
            out_path = config["commands_out"] / src.name
            expected_files.add(out_path)
            content = build_command_file(src, target)
            _write(out_path, content, dry_run, check)

    # 4. Config Sync
    if not only_agent:
        sync_mcp_config(target, dry_run, check)
        if target == "claude":
            sync_claude_settings(dry_run, check)
            sync_claude_keybindings(dry_run, check)

    # 4.5 Skills: symlink .agent/skills/<name>/ into <target>/skills/<name> so
    # they're real, natively-discovered skills (see sync_skills docstring)
    # instead of just files agents self-instruct to Read.
    if not only_agent:
        sync_skills(target, dry_run, check)

    # 5. Cleanup
    if not only_agent and not profile:
        cleanup_orphans(target, expected_files, dry_run)

def _write(path: Path, content: str, dry_run: bool, check: bool):
    try:
        rel = path.relative_to(TARGET_ROOT)
    except ValueError:
        rel = path
    if dry_run:
        print(f"  [DRY] {rel}")
        return
    if check:
        if not path.exists():
            print(f"  [MISSING] {rel}")
            sys.exit(1)
        existing = path.read_text()
        if existing != content:
            print(f"  [DRIFT] {rel}")
            sys.exit(1)
        return
    path.write_text(content)
    print(f"  ✓ {rel}")

def _write_json(path: Path, content: str, dry_run: bool, check: bool):
    """Like _write but compares parsed JSON objects to avoid false positives from formatting."""
    import json as _json
    try:
        rel = path.relative_to(TARGET_ROOT)
    except ValueError:
        rel = path
    if dry_run:
        print(f"  [DRY] {rel}")
        return
    if check:
        if not path.exists():
            print(f"  [MISSING] {rel}")
            sys.exit(1)
        try:
            existing_obj = _json.loads(path.read_text())
            new_obj = _json.loads(content)
            if existing_obj != new_obj:
                print(f"  [DRIFT] {rel}")
                sys.exit(1)
        except _json.JSONDecodeError:
            print(f"  [DRIFT] {rel} (JSON parse error)")
            sys.exit(1)
        return
    path.write_text(content)
    print(f"  ✓ {rel}")

def build_claude_settings() -> str:
    """Generate canonical .claude/settings.json content from this script's constants."""
    import json as _json
    settings = {
        "agent": "orchestrator",
        "enabledMcpjsonServers": [
            "skills-local", "github", "wikipedia", "browser", "filesystem", "shadcn"
        ],
        "enableAllProjectMcpServers": True,
        "permissions": {
            "allow": CLAUDE_PERMISSIONS_ALLOW
        },
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "Bash",
                    "hooks": [
                        {"type": "command", "command": "rtk hook claude"},
                        {"type": "command", "command": _GUARDRAIL_CMD},
                    ]
                }
            ],
            "Stop": [
                {
                    "hooks": [
                        {
                            "type": "command",
                            "command": "python3 .agent/scripts/context/context_autofill.py 2>/dev/null || true"
                        },
                        {
                            "type": "command",
                            "command": "truncate -s0 /tmp/mcp-broker.log 2>/dev/null || true"
                        },
                    ]
                }
            ]
        }
    }
    return _json.dumps(settings, indent=2) + "\n"

def sync_claude_settings(dry_run: bool, check: bool):
    path = TARGET_ROOT / ".claude" / "settings.json"
    content = build_claude_settings()
    _write_json(path, content, dry_run, check)


def sync_claude_keybindings(dry_run: bool, check: bool):
    import json as _json
    path = TARGET_ROOT / ".claude" / "keybindings.json"
    content = _json.dumps(CLAUDE_KEYBINDINGS, indent=2) + "\n"
    _write_json(path, content, dry_run, check)


def sync_skills(target: str, dry_run: bool, check: bool):
    """Expose .agent/skills/<name>/ as native Claude Code / OpenCode skills.

    Claude Code only scans .claude/skills/<name>/SKILL.md (see
    https://code.claude.com/docs/en/skills) and OpenCode only scans
    .opencode/skills/<name>/SKILL.md project-locally (see
    https://opencode.ai/docs/skills/) — .agent/skills/ was never on either
    path, so none of these 160+ knowledge modules were ever real native
    skills for either tool; agents just self-instruct to Read them.

    (OpenCode also auto-discovers .claude/skills/ with no extra config, so
    skills were already reachable there indirectly — this makes it explicit
    and matches the .opencode/agents/ + .opencode/commands/ symmetry with
    .claude/, instead of relying on that implicit cross-tool fallback.)

    Symlinks the whole skill directory rather than copying SKILL.md alone:
    many skills ship supporting files (references/, scripts/, examples/,
    sdks/) that SKILL.md links to with paths relative to its own directory
    (e.g. clickhouse-best-practices/SKILL.md -> references/schema-design.md).
    A symlinked directory keeps those resolving correctly and needs no
    regeneration when skill content changes — unlike agents/commands, which
    are rendered text and must be rewritten by _write() on every edit.
    """
    config = TARGETS.get(target, {})
    skills_out = config.get("skills_out")
    if skills_out is None:
        return  # target has no native skills directory

    skills_out.mkdir(parents=True, exist_ok=True)
    expected_links = set()

    for skill_dir in sorted(p for p in SKILLS_SRC.iterdir() if p.is_dir()):
        if skill_dir.name in SKILL_SKIP_DIRS or not (skill_dir / "SKILL.md").exists():
            continue

        link_path = skills_out / skill_dir.name
        expected_links.add(link_path)
        rel_target = Path(os.path.relpath(skill_dir, skills_out))
        rel_display = link_path.relative_to(TARGET_ROOT)

        if dry_run:
            print(f"  [DRY] {rel_display} -> {rel_target}")
            continue

        if check:
            if not link_path.is_symlink() or Path(os.readlink(link_path)) != rel_target:
                print(f"  [DRIFT] {rel_display}")
                sys.exit(1)
            continue

        if link_path.is_symlink():
            if Path(os.readlink(link_path)) == rel_target:
                print(f"  ✓ {rel_display}")
                continue
            link_path.unlink()
        elif link_path.exists():
            # A real file/directory sits where a symlink belongs — don't
            # clobber something that might be hand-authored; report and skip.
            print(f"  ⚠️  {rel_display} exists and is not a symlink — skipping (remove it manually to let sync manage it)")
            continue

        link_path.symlink_to(rel_target, target_is_directory=True)
        print(f"  🔗 {rel_display} -> {rel_target}")

    # Orphan cleanup: a managed symlink whose source skill no longer exists.
    # Only ever removes symlinks this function itself would create — never a
    # real directory, matching the skip-and-warn behavior above.
    if not check and skills_out.exists():
        for item in sorted(skills_out.iterdir()):
            if item in expected_links or not item.is_symlink():
                continue
            rel = item.relative_to(TARGET_ROOT)
            if dry_run:
                print(f"  [ORPHAN-DRY] {rel}")
            else:
                item.unlink()
                print(f"  🗑️  {rel}")


def _build_provider_section() -> dict:
    """Build opencode provider config pointing to the MCP LLM Broker HTTP API.

    Only tier-level aliases (auto, L1-L4) are registered as models.
    The MCP LLM Broker resolves each alias to a concrete model at runtime
    using router_rules.json — keeping opencode.json fully provider-agnostic.
    """
    port = 11436
    mcp_broker_port = os.environ.get("MCP_BROKER_HTTP_PORT", str(port))

    # Only expose tier aliases — broker resolves to real models via router_rules.json
    models = {alias: {} for alias in ["auto", "L1", "L2", "L3", "L4"]}

    return {
        "mcp-llm-broker": {
            "name": "MCP LLM Broker",
            "npm": "@ai-sdk/openai-compatible",
            "options": {
                "baseURL": f"http://localhost:{mcp_broker_port}/v1",
            },
            "models": models,
        },
    }


def _discover_local_models() -> dict:
    """Discover available models from local LLM backends."""
    import subprocess
    import shutil
    import urllib.request
    import urllib.error
    import json as _json

    models = {}

    # 1. Ollama
    ollama_url = os.environ.get("OLLAMA_HOST", "http://localhost:11434")
    try:
        resp = urllib.request.urlopen(f"{ollama_url}/api/tags", timeout=1)
        data = _json.loads(resp.read())
        for m in data.get("models", []):
            name = m.get("name", "")
            if name:
                models[name] = {}
    except Exception:
        pass

    # 2. Jan / LM Studio (OpenAI-compatible)
    for backend_url in ["http://localhost:1337", "http://localhost:1234"]:
        try:
            resp = urllib.request.urlopen(f"{backend_url}/v1/models", timeout=1)
            data = _json.loads(resp.read())
            for m in data.get("data", []):
                mid = m.get("id", "")
                if mid:
                    models[mid] = {}
        except Exception:
            pass

    return models


# ---------------------------------------------------------------------------
# Router Rules Config Loader
# ---------------------------------------------------------------------------

def _load_router_rules() -> dict:
    """Load .agent/config/router_rules.json and return parsed dict, or empty dict."""
    rules_path = SOURCE_ROOT / ".agent" / "config" / "router_rules.json"
    if not rules_path.exists():
        logging.warning("router_rules.json not found at %s", rules_path)
        return {}
    try:
        import json as _json
        return _json.loads(rules_path.read_text(encoding="utf-8"))
    except Exception as e:
        logging.warning("Failed to parse router_rules.json: %s", e)
        return {}


def _build_model_tier_map(rules: dict) -> dict[str, str]:
    """Extract L1-L4 model mapping from router_rules.json models.ollama section.
    
    Falls back to simple defaults if config is missing.
    """
    models_cfg = rules.get("models", {})
    ollama_cfg = models_cfg.get("ollama", {})
    
    tier_map = {}
    for tier in ["L1", "L2", "L3", "L4"]:
        model = ollama_cfg.get(tier, "")
        if model:
            tier_map[tier] = model
    
    # Fallback defaults
    if not tier_map:
        tier_map = {
            "L1": "llama3.2:3b",
            "L2": "qwen2.5-coder:7b",
            "L3": "qwen2.5-coder:32b",
            "L4": "qwen3-coder:30b",
        }
    
    return tier_map


def _build_agent_tier_map(rules: dict, all_agent_names: list[str]) -> dict[str, str]:
    """Derive agent→tier mapping from router_rules.json.
    
    Strategy (in order):
    1. Match agent name against each rule's `skills` list (exact match)
    2. Match agent name (word-boundary) against each rule's `keywords`
    3. Explicit lookup in `agent_tiers` section of router_rules.json
    4. Match agent `domains` (from frontmatter) against `domain_tiers` section
    5. Default L2
    """
    import re as _re

    rule_list = rules.get("rules", [])
    explicit_tiers = rules.get("agent_tiers", {})
    domain_tiers = rules.get("domain_tiers", {})
    tier_map: dict[str, str] = {}

    # Phase 1: match by skills list (from rules section)
    for rule in rule_list:
        complexity = rule.get("complexity", "L2")
        skills = [s.strip().lower() for s in rule.get("skills", [])]
        for agent in all_agent_names:
            if agent.lower() in skills:
                if agent not in tier_map:
                    tier_map[agent] = complexity

    # Phase 2: match by keywords against agent NAME only (word-boundary)
    for rule in rule_list:
        complexity = rule.get("complexity", "L2")
        keywords = [k.strip().lower() for k in rule.get("keywords", [])]
        for agent in all_agent_names:
            if agent in tier_map:
                continue
            agent_normalized = agent.lower().replace("-", " ").replace("_", " ")
            for kw in keywords:
                pattern = r'(?<![a-z0-9])' + _re.escape(kw) + r'(?![a-z0-9])'
                if _re.search(pattern, agent_normalized):
                    tier_map[agent] = complexity
                    break

    # Phase 3: explicit agent_tiers lookup (from config)
    for agent in all_agent_names:
        if agent in tier_map:
            continue
        if agent in explicit_tiers:
            tier_map[agent] = explicit_tiers[agent]

    # Phase 4: domain_tiers match against agent frontmatter domains
    if domain_tiers:
        agent_domains = _load_agent_domains(all_agent_names)
        for agent in all_agent_names:
            if agent in tier_map:
                continue
            domains = agent_domains.get(agent, [])
            for domain in domains:
                domain_lower = domain.strip().lower()
                if domain_lower in domain_tiers:
                    tier_map[agent] = domain_tiers[domain_lower]
                    break
                # Also check if any domain_tiers key is a substring of the domain
                for dt_key, dt_tier in sorted(domain_tiers.items(),
                                               key=lambda x: -len(x[0])):
                    if dt_key in domain_lower:
                        tier_map[agent] = dt_tier
                        break
                if agent in tier_map:
                    break

    # Phase 5: default L2
    for agent in all_agent_names:
        if agent not in tier_map:
            tier_map[agent] = "L2"

    return tier_map


def _load_agent_domains(agent_names: list[str]) -> dict[str, list[str]]:
    """Read agent domains from frontmatter for domain-tier matching."""
    domains: dict[str, list[str]] = {}
    agents_dir = SOURCE_ROOT / ".agent" / "agents"
    for src in agents_dir.rglob("**/*.md"):
        name = src.stem
        if name not in agent_names:
            continue
        content = src.read_text(encoding="utf-8")
        fm, _ = parse_frontmatter(content)
        raw = fm.get("domains", "")
        # Parse comma-separated or bracket-wrapped list
        raw_clean = raw.strip().strip("[]").strip()
        parts = [d.strip().strip('"').strip("'") for d in raw_clean.split(",") if d.strip()]
        domains[name] = parts
    return domains


def _collect_agent_names() -> list[str]:
    """Return sorted list of all agent names from .agent/agents/."""
    agents_dir = SOURCE_ROOT / ".agent" / "agents"
    if not agents_dir.exists():
        return []
    names = sorted(src.stem for src in agents_dir.rglob("**/*.md") if src.stem)
    return names


def _load_agent_descriptions(agent_names: list[str]) -> dict[str, str]:
    """Read agent descriptions from frontmatter for keyword matching."""
    descs: dict[str, str] = {}
    agents_dir = SOURCE_ROOT / ".agent" / "agents"
    for src in agents_dir.rglob("**/*.md"):
        name = src.stem
        if name not in agent_names:
            continue
        content = src.read_text(encoding="utf-8")
        fm, _ = parse_frontmatter(content)
        descs[name] = fm.get("description", "")
    return descs


# Lazy-loaded router-rules state
_router_rules: dict = {}
_model_tier_map: dict[str, str] = {}
_agent_tier_map: dict[str, str] = {}


def _ensure_router_rules_loaded(all_agent_names: list[str] | None = None):
    """Load router_rules.json once and build tier maps."""
    global _router_rules, _model_tier_map, _agent_tier_map
    if _router_rules:
        return
    _router_rules = _load_router_rules()
    _model_tier_map = _build_model_tier_map(_router_rules)
    if all_agent_names:
        _agent_tier_map = _build_agent_tier_map(_router_rules, all_agent_names)


def _get_agent_model(agent_name: str) -> str:
    """Return a tier-level model alias for an agent (e.g. 'mcp-llm-broker/L2').

    The MCP LLM Broker resolves L1-L4 aliases to concrete models at runtime
    using router_rules.json, making opencode.json provider-agnostic.
    """
    global _agent_tier_map
    tier = _agent_tier_map.get(agent_name, "L2")
    return f"mcp-llm-broker/{tier}"


def _build_agent_section() -> dict:
    """Scan .agent/agents/ and build opencode agent config entries.
    
    Each agent gets mode:"subagent" (except orchestrator which is primary)
    and permissions derived from its tool list.
    """
    agents_dir = SOURCE_ROOT / ".agent" / "agents"
    if not agents_dir.exists():
        return {}

    agent_configs = {}
    primary_agents = {"orchestrator"}  # These remain primary, NOT subagents

    for src in sorted(agents_dir.rglob("**/*.md")):
        name = src.stem
        raw = src.read_text(encoding="utf-8")
        fm, _ = parse_frontmatter(raw)
        agent_name = fm.get("name", name)

        # Determine mode
        if agent_name in primary_agents:
            continue  # Skip primary agents (they use default_agent)

        # Parse tools to derive permissions
        tools_str = fm.get("tools") or AGENT_DEFAULT_TOOLS.get(agent_name, "")
        tools_clean = str(tools_str).strip().strip("[]").strip()
        tools = [t.strip().strip('"').strip("'") for t in tools_clean.split(",") if t.strip()]

        permissions = {}
        tool_to_perm = {
            "Read":  "read",
            "Write": "edit",
            "Edit":  "edit",
            "Bash":  "bash",
            "Glob":  "glob",
            "Grep":  "grep",
        }
        for tool_name, perm_name in tool_to_perm.items():
            if any(t == tool_name or t.startswith(tool_name) for t in tools):
                permissions[perm_name] = "allow"

        # Fallback: if no tools parsed, give read-only
        if not permissions:
            permissions["read"] = "allow"

        entry = {
            "mode": "subagent",
            "permission": permissions,
            "description": fm.get("description", f"Specialist: {agent_name}"),
        }

        # If agent has a 'model' field in frontmatter, preserve it
        if fm.get("model") and fm["model"] != "inherit":
            entry["model"] = fm["model"]

        # Hide from @ autocomplete to reduce noise (still callable via task())
        entry["hidden"] = True

        agent_configs[agent_name] = entry

    return agent_configs


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", choices=["claude", "opencode"], default="claude")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--agent", metavar="NAME", default="")
    parser.add_argument("--profile", metavar="NAME", default="")
    parser.add_argument("--no-commands", action="store_true")
    parser.add_argument("--no-workflows", action="store_true")
    parser.add_argument("--root", metavar="PATH", help="Override repository root path")
    args = parser.parse_args()

    if args.root:
        global TARGET_ROOT, TARGETS
        TARGET_ROOT = Path(args.root).resolve()
        
        # Redefine TARGETS based on the new TARGET_ROOT
        TARGETS["claude"]["agents_out"]   = TARGET_ROOT / ".claude" / "agents"
        TARGETS["claude"]["commands_out"] = TARGET_ROOT / ".claude" / "commands"
        TARGETS["claude"]["skills_out"]   = TARGET_ROOT / ".claude" / "skills"
        TARGETS["opencode"]["agents_out"]   = TARGET_ROOT / ".opencode" / "agents"
        TARGETS["opencode"]["commands_out"] = TARGET_ROOT / ".opencode" / "commands"
        TARGETS["opencode"]["skills_out"]   = TARGET_ROOT / ".opencode" / "skills"
        TARGETS["opencode"]["config_out"]   = TARGET_ROOT / "opencode.json"

    sync(args.target, args.dry_run, args.check, args.agent, args.profile, args.no_commands, args.no_workflows)

if __name__ == "__main__":
    main()
