#!/usr/bin/env python3
"""
sync_agents.py — Generate .claude/ and .opencode/ agent layers from .agent/

This script universalizes the agent infrastructure by syncing the source of truth (.agent/)
to client-specific directories (.claude/ for Claude Code, .opencode/ for OpenCode).

Usage:
    python3 .agent/scripts/delivery/sync_agents.py --target claude
    python3 .agent/scripts/delivery/sync_agents.py --target opencode
"""

# Antigravity Domain-Aware Import Logic
try:
    from lib.paths import REPO_ROOT
except ImportError:
    import sys
    from pathlib import Path
    SCRIPTS_DIR = Path(__file__).resolve().parents[1]
    if str(SCRIPTS_DIR) not in sys.path:
        sys.path.append(str(SCRIPTS_DIR))
    for domain in ["health", "context", "delivery", "orchestration", "analysis", "models", "knowledge", "dev"]:
        d_path = str(SCRIPTS_DIR / domain)
        if d_path not in sys.path:
            sys.path.append(d_path)


import argparse
import sys
import os
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent.parent.parent.resolve()
SOURCE_ROOT = REPO_ROOT
TARGET_ROOT = REPO_ROOT

AGENTS_SRC    = SOURCE_ROOT / ".agent" / "agents"
WORKFLOWS_SRC = SOURCE_ROOT / ".agent" / "workflows"
SKILLS_SRC    = SOURCE_ROOT / ".agent" / "skills"

# Targets Configuration
TARGETS = {
    "claude": {
        "agents_out":   TARGET_ROOT / ".claude" / "agents",
        "commands_out": TARGET_ROOT / ".claude" / "commands",
        "header": "<!-- GENERATED by sync_agents.py (target: claude) — do not edit directly -->\n",
        "workflow_prefix": "wf-",
    },
    "opencode": {
        "agents_out":   TARGET_ROOT / ".opencode" / "agents",
        "commands_out": TARGET_ROOT / ".opencode" / "commands",
        "config_out":   TARGET_ROOT / "opencode.json",
        "header": "<!-- GENERATED by sync_agents.py (target: opencode) — do not edit directly -->\n",
        "workflow_prefix": "", # OpenCode prefers direct names or categories
    }
}

WORKFLOW_DEFAULT_TOOLS = "Read, Grep, Glob, Bash, Write, Edit"

AGENT_DEFAULT_TOOLS: dict[str, str] = {
    "orchestrator":           "Read, Write, Edit, Bash, Grep, Glob, Agent",
    "analyst":                "Read, Write, Edit, Grep, Glob, Agent",
    "project-planner":        "Read, Write, Edit, Grep, Glob, Agent",
    "ai-engineer":            "Read, Write, Edit, Bash, Grep, Glob, Agent",
    "backend-specialist":     "Read, Write, Edit, Bash, Grep, Glob",
    "frontend-specialist":    "Read, Write, Edit, Bash, Grep, Glob",
    "crypto-go-architect":   "Read, Write, Edit, Bash, Grep, Glob",
    "database-architect":     "Read, Write, Edit, Bash, Grep, Glob",
    "mobile-developer":       "Read, Write, Edit, Bash, Grep, Glob",
    "game-developer":         "Read, Write, Edit, Bash, Grep, Glob",
    "devops-engineer":        "Read, Write, Edit, Bash, Grep, Glob",
    "k8s-engineer":           "Read, Write, Edit, Bash, Grep, Glob",
    "data-engineer":          "Read, Write, Edit, Bash, Grep, Glob",
    "grpc-architect":         "Read, Write, Edit, Bash, Grep, Glob",
    "test-engineer":          "Read, Write, Edit, Bash, Grep, Glob",
    "qa-automation-engineer": "Read, Write, Edit, Bash, Grep, Glob",
    "code-archaeologist":     "Read, Write, Edit, Bash, Grep, Glob",
    "debugger":               "Read, Bash, Grep, Glob",
    "performance-optimizer":  "Read, Bash, Grep, Glob, Write",
    "security-auditor":       "Read, Bash, Grep, Glob",
    "penetration-tester":     "Read, Bash, Grep, Glob",
    "explorer-agent":         "Read, Bash, Grep, Glob",
    "git-master":             "Read, Bash, Grep, Glob",
    "reviewer":               "Read, Bash, Grep, Glob, Write",
    "documentation-writer":   "Read, Write, Edit, Grep, Glob",
    "wiki-architect":         "Read, Write, Edit, Grep, Glob",
    "rest-api-designer":      "Read, Write, Edit, Grep, Glob",
    "seo-specialist":         "Read, Write, Grep, Glob",
    "product-manager":        "Read, Write, Grep, Glob",
    "product-owner":          "Read, Write, Grep, Glob",
    "python-specialist":      "Read, Write, Edit, Bash, Grep, Glob",
    # Previously using workflow defaults — now explicit.
    # Note: agents with 'tools:' in their source frontmatter use that value;
    # entries here apply only when frontmatter has no tools field.
    "archivist":              "Read, Write, Edit, Grep, Glob, Bash",
    "chaos-monkey":           "Read, Bash, Grep, Glob",
    "cto":                    "Read, Write, Edit, Grep, Glob, Agent",
    "ethics-auditor":         "Read, Grep, Glob",
    "maintainer":             "Read, Write, Edit, Bash, Grep, Glob",
    "red-team":               "Read, Bash, Grep, Glob",
    "release-manager":        "Read, Write, Edit, Bash, Grep, Glob",
    "risk-manager":           "Read, Write, Edit, Grep, Glob",
    "visual-designer":        "Read, Write, Grep, Glob",
    # cloud-engineer, crypto-specialist, go-specialist, grafana-master,
    # paperclip, prompt-specialist, sre-engineer — tools defined in frontmatter
}

COMMAND_META: dict[str, dict] = {
    "debug": {
        "argument-hint": "<error or issue description>",
        "allowed-tools": "Read, Grep, Glob, Bash",
    },
    "plan": {
        "argument-hint": "<feature or task to plan>",
        "allowed-tools": "Read, Grep, Glob, Write",
    },
    "create": {
        "argument-hint": "<app description, e.g. todo app with auth>",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit, Agent",
    },
    "deploy": {
        "argument-hint": "[environment: staging|production]",
        "allowed-tools": "Read, Bash",
    },
    "enhance": {
        "argument-hint": "<feature or improvement description>",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit",
    },
    "orchestrate": {
        "argument-hint": "<complex multi-domain task>",
        "allowed-tools": "Read, Grep, Glob, Bash, Write, Edit, Agent",
    },
    "status": {
        "argument-hint": "",
        "allowed-tools": "Read, Grep, Bash",
    },
}

# Skills injected by the sync script into agent files (in addition to frontmatter skills).
# Covers the 31 skills that exist in .agent/skills/ but are not referenced in any agent .md.
AGENT_SKILL_EXTRAS: dict[str, list[str]] = {
    "orchestrator":           ["dispatching-parallel-agents", "agent-routing-pro"],
    "ai-engineer":            ["mcp-integration", "hook-development", "skill-creator",
                               "agent-development", "command-development"],
    "backend-specialist":     ["api-development", "postgres-best-practices", "typed-service-contracts",
                               "better-auth-best-practices", "convex-setup-auth", "paperclip-worker"],
    "frontend-specialist":    ["shadcn-best-practices", "next-best-practices", "ui-ux-pro-max",
                               "browser-use", "playwright-best-practices",
                               "better-auth-best-practices", "paperclip-worker"],
    "mobile-developer":       ["paperclip-worker"],
    "go-specialist":          ["paperclip-worker"],
    "test-engineer":          ["test-driven-development", "verification-before-completion"],
    "qa-automation-engineer": ["playwright-best-practices", "browser-use", "agent-browser"],
    "devops-engineer":        ["github-actions-expert", "sentry-cli-expert"],
    "sre-engineer":           ["sentry-cli-expert"],
    "database-architect":     ["postgres-best-practices", "turso-db", "supabase-postgres-best-practices"],
    "data-engineer":          ["nextflow-development"],
    "archivist":              ["semantic-search"],
    "reviewer":               ["verification-before-completion", "requesting-code-review"],
    "prompt-specialist":      ["prompts-best-practices", "skill-creator",
                               "agent-development", "command-development"],
    "visual-designer":        ["visual-explainer"],
    "analyst":                ["scientific-problem-selection"],
}

# Read-only Bash and MCP operations that should not prompt the user each time.
CLAUDE_PERMISSIONS_ALLOW = [
    "Bash(git status)",
    "Bash(git log*)",
    "Bash(git diff*)",
    "Bash(git branch*)",
    "Bash(ls*)",
    "Bash(find . *)",
    "Bash(python3 .agent/scripts/health/status_report.py)",
    "Bash(python3 .agent/scripts/delivery/sync_agents.py --check*)",
    "Bash(python3 .agent/scripts/dev/checklist.py*)",
    "mcp__local-skill-server__*",
    "mcp__github__get_*",
    "mcp__github__list_*",
    "mcp__github__search_*",
    "mcp__filesystem__read_*",
    "mcp__filesystem__list_*",
    "mcp__wikipedia__*",
]

# Inline guardrail command — kept here so settings.json can be fully generated.
_GUARDRAIL_CMD = (
    "python3 -c \"\n"
    "import json, sys, subprocess, os\n"
    "data = json.load(sys.stdin)\n"
    "cmd = data.get('tool_input', {}).get('command', '')\n"
    "if not cmd:\n"
    "    sys.exit(0)\n"
    "# Walk up to find the project root (contains .agent/scripts/guardrail_monitor.py)\n"
    "root = os.getcwd()\n"
    "for _ in range(6):\n"
    "    script = os.path.join(root, '.agent/scripts/health/guardrail_monitor.py')\n"
    "    if os.path.isfile(script):\n"
    "        break\n"
    "    parent = os.path.dirname(root)\n"
    "    if parent == root:\n"
    "        script = None\n"
    "        break\n"
    "    root = parent\n"
    "else:\n"
    "    script = None\n"
    "if not script:\n"
    "    sys.exit(0)\n"
    "result = subprocess.run(\n"
    "    ['python3', script, '--check-cmd', cmd],\n"
    "    capture_output=True, text=True\n"
    ")\n"
    "if result.returncode == 2:\n"
    "    print(result.stdout.strip())\n"
    "    sys.exit(2)\n"
    "sys.exit(0)\n"
    "\""
)

CLAUDE_KEYBINDINGS = [
    {"key": "ctrl+shift+o", "command": "/orchestrate"},
    {"key": "ctrl+shift+d", "command": "/debug"},
    {"key": "ctrl+shift+s", "command": "/status"},
    {"key": "ctrl+shift+r", "command": "/reviewer"},
    {"key": "ctrl+shift+t", "command": "/test"},
    {"key": "ctrl+shift+c", "command": "/create"},
]

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def parse_frontmatter(content: str) -> tuple[dict, str]:
    if not content.startswith("---"):
        return {}, content
    end = content.find("\n---", 3)
    if end == -1:
        return {}, content
    fm_block = content[3:end].strip()
    body = content[end + 4:].lstrip("\n")
    frontmatter: dict = {}
    for line in fm_block.splitlines():
        if ":" in line:
            key, _, val = line.partition(":")
            frontmatter[key.strip()] = val.strip()
    return frontmatter, body

def render_frontmatter(fm: dict) -> str:
    lines = ["---"]
    for key, val in fm.items():
        if val: lines.append(f"{key}: {val}")
        else: lines.append(f"{key}:")
    lines.append("---")
    return "\n".join(lines) + "\n"

def skill_exists(skill_name: str) -> bool:
    return (SKILLS_SRC / skill_name / "SKILL.md").exists()

# ---------------------------------------------------------------------------
# Builders
# ---------------------------------------------------------------------------

def build_agent_file(src_path: Path, target: str, is_workflow: bool = False) -> str:
    raw = src_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(raw)
    agent_name = src_path.stem
    skills = [s.strip() for s in fm.get("skills", "").split(",") if s.strip()]

    clean_fm: dict = {}
    clean_fm["name"] = fm.get("name", agent_name)
    if fm.get("description"): clean_fm["description"] = fm["description"]

    # Target specific logic
    if target == "claude":
        clean_fm["tools"] = fm.get("tools") or AGENT_DEFAULT_TOOLS.get(agent_name) or WORKFLOW_DEFAULT_TOOLS
    elif target == "opencode":
        # OpenCode might use standard frontmatter
        if fm.get("model"): clean_fm["model"] = fm["model"]

    parts = [TARGETS[target]["header"], render_frontmatter(clean_fm)]
    
    if is_workflow and target == "claude":
        body = body.replace("$ARGUMENTS", "_Context from user message is passed automatically by Claude Code._")
    
    parts.append(body)

    if target == "claude" and not is_workflow:
        extras = AGENT_SKILL_EXTRAS.get(agent_name, [])
        all_skills = list(dict.fromkeys(skills + extras))  # merge, dedup, preserve order
        skill_lines = "\n".join(f"- `.agent/skills/{s}/SKILL.md`" for s in all_skills if skill_exists(s))
        if skill_lines:
            parts.append("\n---\n\n> **Skills** — read these files with the `Read` tool before starting:\n" + skill_lines + "\n")

    return "\n".join(parts)

def build_command_file(src_path: Path, target: str) -> str:
    raw = src_path.read_text(encoding="utf-8")
    fm, body = parse_frontmatter(raw)
    name = src_path.stem
    meta = COMMAND_META.get(name, {})

    cmd_fm: dict = {}
    if fm.get("description"): cmd_fm["description"] = fm["description"]

    if target == "claude":
        cmd_fm["argument-hint"] = meta.get("argument-hint", "")
        cmd_fm["allowed-tools"] = meta.get("allowed-tools", WORKFLOW_DEFAULT_TOOLS)
    elif target == "opencode":
        # OpenCode commands often specify an agent or mode
        cmd_fm["agent"] = fm.get("agent", "orchestrator")
        if meta.get("argument-hint"):
            body = f"> Hint: {meta['argument-hint']}\n\n" + body

    parts = [TARGETS[target]["header"], render_frontmatter(cmd_fm), body]
    return "\n".join(parts)

# ---------------------------------------------------------------------------
# Sync Logic
# ---------------------------------------------------------------------------

def cleanup_orphans(target: str, expected_files: set, dry_run: bool):
    config = TARGETS[target]
    for out_dir in [config["agents_out"], config["commands_out"]]:
        if not out_dir.exists():
            continue
        for item in out_dir.glob("*.md"):
            if item not in expected_files:
                rel = item.relative_to(REPO_ROOT)
                if dry_run:
                    print(f"  [ORPHAN-DRY] {rel}")
                else:
                    item.unlink()
                    print(f"  🗑️ {rel}")

def get_profile_extra_agents(profile_name: str) -> set:
    if not profile_name:
        return set()
    profile_path = REPO_ROOT / ".github" / "profiles.yml"
    if not profile_path.exists():
        return set()
    try:
        import yaml
        with open(profile_path) as f:
            data = yaml.safe_load(f)
            return set(data.get("profiles", {}).get(profile_name, {}).get("extra_agents", []))
    except Exception:
        return set()

def should_include_agent(src: Path, profile_name: str, extra_agents: set) -> bool:
    if not profile_name:
        return True
    if src.stem in extra_agents:
        return True
    
    # Check frontmatter
    content = src.read_text()
    if not content.startswith("---"):
        return True # Universal if no frontmatter
        
    parts = content.split("---", 2)
    if len(parts) < 3:
        return True
        
    try:
        import yaml
        fm = yaml.safe_load(parts[1])
        agent_profiles = fm.get("profile", "")
        if not agent_profiles:
            return True # Universal
        
        allowed = [p.strip() for p in str(agent_profiles).split(",")]
        return profile_name in allowed
    except Exception:
        return True # Fallback to include

def sync_mcp_config(target: str, dry_run: bool, check: bool):
    if target != "opencode":
        return # Claude uses symlinks or global config
    
    src_path = SOURCE_ROOT / ".agent" / "config" / "mcp_config.json"
    dest_path = TARGETS[target].get("config_out")
    
    if not src_path.exists() or not dest_path:
        return

    import json
    try:
        with open(src_path, "r") as f:
            src_data = json.load(f)
        
        # Always use the latest instructions and permissions from the hub template
        base_template = {
            "$schema": "https://opencode.ai/config.json",
            "default_agent": "orchestrator",
            "instructions": [
                ".agent/agents/core/orchestrator.md",
                ".agent/rules/gemini/00_protocol.md",
                ".agent/rules/gemini/01_classifier.md",
                ".agent/rules/gemini/02_routing.md",
                ".agent/rules/ADAPTIVE_ROUTING.md",
                ".agent/rules/gemini/03_gateway.md",
                ".agent/rules/gemini/04_tier0_universal.md",
                ".agent/rules/gemini/05_tier1_code.md",
                ".agent/rules/gemini/06_tier2_design.md",
                ".agent/rules/gemini/07_reference.md",
                ".agent/rules/LESSONS_LEARNED.md"
            ],
            "permission": {
                "shell": "allow",
                "file": "allow",
                "network": "allow"
            },
            "mcp": {}
        }

        if dest_path.exists():
            with open(dest_path, "r") as f:
                dest_data = json.load(f)
            # Provisioning: Always overwrite core sections from hub
            dest_data["instructions"] = base_template["instructions"]
            dest_data["permission"] = base_template["permission"]
            dest_data["$schema"] = base_template["$schema"]
            dest_data["default_agent"] = base_template["default_agent"]
        else:
            dest_data = base_template
        
        mcp_servers = src_data.get("mcpServers", {})
        converted = {}
        
        for name, cfg in mcp_servers.items():
            # Convert Claude style to OpenCode style
            cmd_array = [cfg.get("command", "")]
            cmd_array.extend(cfg.get("args", []))
            
            converted[name] = {
                "type": "local",
                "command": [c for c in cmd_array if c],
                "enabled": cfg.get("enabled", True),
                "env": cfg.get("env", {})
            }
        
        dest_data["mcp"] = converted
        
        new_content = json.dumps(dest_data, indent=2) + "\n"
        
        if check:
            if not dest_path.exists():
                print(f"  [MISSING] {dest_path.relative_to(REPO_ROOT)}")
                sys.exit(1)
            existing = dest_path.read_text()
            if existing.strip() != new_content.strip():
                print(f"  [DRIFT] {dest_path.relative_to(REPO_ROOT)}")
                sys.exit(1)
            return

        if not dry_run:
            dest_path.write_text(new_content)
            print(f"  ✓ {dest_path.relative_to(REPO_ROOT)} (MCP Synced)")
        else:
            print(f"  [DRY] {dest_path.relative_to(REPO_ROOT)} (MCP Sync)")
            
    except Exception as e:
        print(f"  ⚠️ Failed to sync MCP config: {e}")

def sync(target: str, dry_run: bool = False, check: bool = False, only_agent: str = "", profile: str = "", no_commands: bool = False, no_workflows: bool = False):
    config = TARGETS[target]
    config["agents_out"].mkdir(parents=True, exist_ok=True)
    config["commands_out"].mkdir(parents=True, exist_ok=True)

    print(f"\n=== Syncing TARGET: {target} ===")
    print(f"  Source: {SOURCE_ROOT}")
    print(f"  Target: {TARGET_ROOT}")
    
    expected_files = set()
    extra_agents = get_profile_extra_agents(profile)

    # 1. Specialist Agents
    agent_files = sorted(AGENTS_SRC.rglob("**/*.md"))
    if only_agent:
        agent_files = [f for f in agent_files if f.stem == only_agent]
    
    for src in agent_files:
        if not should_include_agent(src, profile, extra_agents):
            continue
            
        out_path = config["agents_out"] / src.name
        expected_files.add(out_path)
        content = build_agent_file(src, target, is_workflow=False)
        _write(out_path, content, dry_run, check)

    # 2. Workflows as Agents (Claude only usually)
    if target == "claude" and not no_workflows:
        for src in sorted(WORKFLOWS_SRC.glob("*.md")):
            # Workflows are generally universal unless we add profile support for them too
            out_path = config["agents_out"] / f"wf-{src.name}"
            expected_files.add(out_path)
            content = build_agent_file(src, target, is_workflow=True)
            _write(out_path, content, dry_run, check)

    # 3. Workflows as Commands
    if not no_commands:
        for src in sorted(WORKFLOWS_SRC.glob("*.md")):
            out_path = config["commands_out"] / src.name
            expected_files.add(out_path)
            content = build_command_file(src, target)
            _write(out_path, content, dry_run, check)

    # 4. Config Sync
    if not only_agent:
        sync_mcp_config(target, dry_run, check)
        if target == "claude":
            sync_claude_settings(dry_run, check)
            sync_claude_keybindings(dry_run, check)

    # 5. Cleanup
    if not only_agent and not profile:
        cleanup_orphans(target, expected_files, dry_run)

def _write(path: Path, content: str, dry_run: bool, check: bool):
    try:
        rel = path.relative_to(TARGET_ROOT)
    except ValueError:
        rel = path
    if dry_run:
        print(f"  [DRY] {rel}")
        return
    if check:
        if not path.exists():
            print(f"  [MISSING] {rel}")
            sys.exit(1)
        existing = path.read_text()
        if existing != content:
            print(f"  [DRIFT] {rel}")
            sys.exit(1)
        return
    path.write_text(content)
    print(f"  ✓ {rel}")

def _write_json(path: Path, content: str, dry_run: bool, check: bool):
    """Like _write but compares parsed JSON objects to avoid false positives from formatting."""
    import json as _json
    try:
        rel = path.relative_to(TARGET_ROOT)
    except ValueError:
        rel = path
    if dry_run:
        print(f"  [DRY] {rel}")
        return
    if check:
        if not path.exists():
            print(f"  [MISSING] {rel}")
            sys.exit(1)
        try:
            existing_obj = _json.loads(path.read_text())
            new_obj = _json.loads(content)
            if existing_obj != new_obj:
                print(f"  [DRIFT] {rel}")
                sys.exit(1)
        except _json.JSONDecodeError:
            print(f"  [DRIFT] {rel} (JSON parse error)")
            sys.exit(1)
        return
    path.write_text(content)
    print(f"  ✓ {rel}")

def build_claude_settings() -> str:
    """Generate canonical .claude/settings.json content from this script's constants."""
    import json as _json
    settings = {
        "agent": "orchestrator",
        "enabledMcpjsonServers": [
            "skills-local", "github", "wikipedia", "browser", "filesystem", "shadcn"
        ],
        "enableAllProjectMcpServers": True,
        "permissions": {
            "allow": CLAUDE_PERMISSIONS_ALLOW
        },
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "Bash",
                    "hooks": [{"type": "command", "command": _GUARDRAIL_CMD}]
                }
            ],
            "Stop": [
                {
                    "hooks": [{
                        "type": "command",
                        "command": "python3 .agent/scripts/context/context_autofill.py 2>/dev/null || true"
                    }]
                }
            ]
        }
    }
    return _json.dumps(settings, indent=2) + "\n"

def sync_claude_settings(dry_run: bool, check: bool):
    path = TARGET_ROOT / ".claude" / "settings.json"
    content = build_claude_settings()
    _write_json(path, content, dry_run, check)

def sync_claude_keybindings(dry_run: bool, check: bool):
    import json as _json
    path = TARGET_ROOT / ".claude" / "keybindings.json"
    content = _json.dumps(CLAUDE_KEYBINDINGS, indent=2) + "\n"
    _write_json(path, content, dry_run, check)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", choices=["claude", "opencode"], default="claude")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--agent", metavar="NAME", default="")
    parser.add_argument("--profile", metavar="NAME", default="")
    parser.add_argument("--no-commands", action="store_true")
    parser.add_argument("--no-workflows", action="store_true")
    parser.add_argument("--root", metavar="PATH", help="Override repository root path")
    args = parser.parse_args()

    if args.root:
        global TARGET_ROOT, TARGETS
        TARGET_ROOT = Path(args.root).resolve()
        
        # Redefine TARGETS based on the new TARGET_ROOT
        TARGETS["claude"]["agents_out"]   = TARGET_ROOT / ".claude" / "agents"
        TARGETS["claude"]["commands_out"] = TARGET_ROOT / ".claude" / "commands"
        TARGETS["opencode"]["agents_out"]   = TARGET_ROOT / ".opencode" / "agents"
        TARGETS["opencode"]["commands_out"] = TARGET_ROOT / ".opencode" / "commands"
        TARGETS["opencode"]["config_out"]   = TARGET_ROOT / "opencode.json"

    sync(args.target, args.dry_run, args.check, args.agent, args.profile, args.no_commands, args.no_workflows)

if __name__ == "__main__":
    main()
