#!/usr/bin/env python3

# Antigravity Domain-Aware Import Logic
try:
    from lib.paths import REPO_ROOT
except ImportError:
    import sys
    from pathlib import Path
    SCRIPTS_DIR = Path(__file__).resolve().parents[1]
    if str(SCRIPTS_DIR) not in sys.path:
        sys.path.append(str(SCRIPTS_DIR))
    for domain in ["health", "context", "delivery", "orchestration", "analysis", "models", "knowledge", "dev"]:
        d_path = str(SCRIPTS_DIR / domain)
        if d_path not in sys.path:
            sys.path.append(d_path)

import os
import sys
import argparse
from pathlib import Path
from datetime import datetime
import re

# Ensure we can import from lib
sys.path.append(str(Path(__file__).resolve().parent.parent))
from lib.common import load_json_safe, save_json_atomic, render_task_card
from lib.paths import REPO_ROOT

def slugify(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9]+', '-', text)
    return text.strip('-')[:30]

def mine_roadmap():
    roadmap_paths = [
        REPO_ROOT / "ROADMAP.md",
        REPO_ROOT / "wiki" / "ROADMAP.md"
    ]
    
    content = ""
    source = None
    for p in roadmap_paths:
        if p.exists():
            content = p.read_text(encoding="utf-8")
            source = p
            break
            
    if not content:
        print("❌ No ROADMAP.md found.")
        return []

    # Simple logic: extract items from "## Planned" or similar sections
    # In a real scenario, this would use an LLM via the Agent tool
    # But for the script, we provide the parsing logic that the agent can invoke
    
    tasks = []
    lines = content.split('\n')
    current_section = ""
    
    for line in lines:
        if line.startswith('## '):
            current_section = line[3:].strip()
        elif line.strip().startswith('- [ ]') or line.strip().startswith('- '):
            task_text = line.strip().replace('- [ ]', '').replace('- ', '').strip()
            keywords = ["planned", "todo", "backlog", "upcoming"]
            if task_text and any(k in current_section.lower() for k in keywords):
                tasks.append({
                    "title": task_text,
                    "section": current_section
                })
                
    return tasks

def create_task_card(task):
    date_str = datetime.now().strftime("%Y-%m-%d")
    slug = slugify(task['title'])
    filename = f"{date_str}-{slug}.md"
    filepath = REPO_ROOT / "tasks" / filename
    
    if filepath.exists():
        print(f"⚠️ Task already exists: {filename}")
        return False
        
    if not (REPO_ROOT / "tasks").exists():
        (REPO_ROOT / "tasks").mkdir(parents=True)

    # NOTE: tags as [STORY] but renders via the ad-hoc TASK_CARD.md shape, not the BMAD
    # STORY.md template render_task_card()'s own docstring says [STORY] should use. Pre-existing
    # mislabeling, deliberately left as-is here — see the "Open questions" in
    # tasks/done/2026-08/2026-08-14-unify-task-card-template-single-source-of-truth.md.
    try:
        content = render_task_card(
            tag="STORY", title=task['title'], date=date_str, agent="orchestrator", priority="Medium",
            source=f"task_miner (ROADMAP.md, section: {task['section']})",
            problem=f"Extracted from Roadmap ({task['section']}): {task['title']}",
            acceptance_criteria=(
                "- [ ] Implement feature based on roadmap description\n"
                "- [ ] Verify functionality\n"
                "- [ ] Add tests"
            ),
            context="Autonomously generated by Task Miner.",
        )
    except FileNotFoundError:
        # Missing TASK_CARD.md must degrade to a minimal card, not crash the miner run.
        content = f"# [STORY] {task['title']}\n\n## Problem\nExtracted from Roadmap ({task['section']}): {task['title']}\n\n## Context\nAutonomously generated by Task Miner.\n"
    filepath.write_text(content, encoding="utf-8")
    print(f"✅ Created task: {filename}")
    return True

def main():
    parser = argparse.ArgumentParser(description="Mine ROADMAP.md for new tasks.")
    parser.add_argument("--dry-run", action="store_true", help="Don't write files.")
    args = parser.parse_args()
    
    print(f"🔍 Mining roadmap in {REPO_ROOT}...")
    tasks = mine_roadmap()
    
    if not tasks:
        print("ℹ️ No new tasks found in roadmap.")
        return
        
    created_count = 0
    for t in tasks:
        if args.dry_run:
            print(f"Found: {t['title']}")
        else:
            if create_task_card(t):
                created_count += 1
                
    print(f"✨ Done. Mined {created_count} new tasks.")

if __name__ == "__main__":
    main()
